// Copyright (c) 2003 Sun Microsystems, Inc.  All Rights Reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
//
// Redistribution of source code must retain the above copyright
// notice, this list of conditions and the following disclaimer.
//
// Redistribution in binary form must reproduce the above copyright
// notice, this list of conditions and the following disclaimer in the
// documentation and/or other materials provided with the distribution.
//
// Neither the name of Sun Microsystems, Inc. or the names of
// contributors may be used to endorse or promote products derived
// from this software without specific prior written permission.
//
// This software is provided "AS IS," without a warranty of any kind.
// ALL EXPRESS OR IMPLIED CONDITIONS, REPRESENTATIONS AND WARRANTIES,
// INCLUDING ANY IMPLIED WARRANTY OF MERCHANTABILITY, FITNESS FOR A
// PARTICULAR PURPOSE OR NON-INFRINGEMENT, ARE HEREBY EXCLUDED.
// SUN MICROSYSTEMS, INC. ("SUN") AND ITS LICENSORS SHALL NOT BE LIABLE
// FOR ANY DAMAGES SUFFERED BY LICENSEE AS A RESULT OF USING, MODIFYING
// OR DISTRIBUTING THIS SOFTWARE OR ITS DERIVATIVES.  IN NO EVENT WILL
// SUN OR ITS LICENSORS BE LIABLE FOR ANY LOST REVENUE, PROFIT OR DATA,
// OR FOR DIRECT, INDIRECT, SPECIAL, CONSEQUENTIAL, INCIDENTAL OR
// PUNITIVE DAMAGES, HOWEVER CAUSED AND REGARDLESS OF THE THEORY OF
// LIABILITY, ARISING OUT OF THE USE OF OR INABILITY TO USE THIS SOFTWARE,
// EVEN IF SUN HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
//

//! JEDEC JEP106 (2003) and SPD decoding tables from `lib/dimm_spd.c`.
//! Regenerate with `python3 tools/gen-spd-tables.py` after changing the C tables.

const c = @import("ipmi_c");

pub const spd_memtype_vals = [_]c.struct_valstr{
    .{ .val = 0x01, .str = "STD FPM DRAM" },
    .{ .val = 0x02, .str = "EDO" },
    .{ .val = 0x04, .str = "SDRAM" },
    .{ .val = 0x05, .str = "ROM" },
    .{ .val = 0x06, .str = "DDR SGRAM" },
    .{ .val = 0x07, .str = "DDR SDRAM" },
    .{ .val = 0x08, .str = "DDR2 SDRAM" },
    .{ .val = 0x09, .str = "DDR2 SDRAM FB-DIMM" },
    .{ .val = 0x0A, .str = "DDR2 SDRAM FB-DIMM Probe" },
    .{ .val = 0x0B, .str = "DDR3 SDRAM" },
    .{ .val = 0x0C, .str = "DDR4 SDRAM" },
    .{ .val = 0x00, .str = null },
};

pub const ddr3_density_vals = [_]c.struct_valstr{
    .{ .val = 0, .str = "256 Mb" },
    .{ .val = 1, .str = "512 Mb" },
    .{ .val = 2, .str = "1 Gb" },
    .{ .val = 3, .str = "2 Gb" },
    .{ .val = 4, .str = "4 Gb" },
    .{ .val = 5, .str = "8 Gb" },
    .{ .val = 6, .str = "16 Gb" },
    .{ .val = 0x00, .str = null },
};

pub const ddr3_banks_vals = [_]c.struct_valstr{
    .{ .val = 0, .str = "3 (8 Banks)" },
    .{ .val = 1, .str = "4 (16 Banks)" },
    .{ .val = 2, .str = "5 (32 Banks)" },
    .{ .val = 3, .str = "6 (64 Banks)" },
    .{ .val = 0x00, .str = null },
};

pub const ddr3_ecc_vals = [_]c.struct_valstr{
    .{ .val = 0, .str = "0 bits" },
    .{ .val = 1, .str = "8 bits" },
    .{ .val = 0x00, .str = null },
};

pub const ddr4_density_vals = [_]c.struct_valstr{
    .{ .val = 0, .str = "256 Mb" },
    .{ .val = 1, .str = "512 Mb" },
    .{ .val = 2, .str = "1 Gb" },
    .{ .val = 3, .str = "2 Gb" },
    .{ .val = 4, .str = "4 Gb" },
    .{ .val = 5, .str = "8 Gb" },
    .{ .val = 6, .str = "16 Gb" },
    .{ .val = 7, .str = "32 Gb" },
    .{ .val = 0x00, .str = null },
};

pub const ddr4_banks_vals = [_]c.struct_valstr{
    .{ .val = 0, .str = "2 (4 Banks)" },
    .{ .val = 1, .str = "3 (8 Banks)" },
    .{ .val = 0x00, .str = null },
};

pub const ddr4_bank_groups = [_]c.struct_valstr{
    .{ .val = 0, .str = "0 (no Bank Groups)" },
    .{ .val = 1, .str = "1 (2 Bank Groups)" },
    .{ .val = 2, .str = "2 (4 Bank Groups)" },
    .{ .val = 0x00, .str = null },
};

pub const ddr4_package_type = [_]c.struct_valstr{
    .{ .val = 0, .str = "Monolithic DRAM Device" },
    .{ .val = 1, .str = "Non-Monolithic Device" },
    .{ .val = 0x00, .str = null },
};

pub const ddr4_technology_type = [_]c.struct_valstr{
    .{ .val = 0, .str = "Extended module type, see byte 15" },
    .{ .val = 1, .str = "RDIMM" },
    .{ .val = 2, .str = "UDIMM" },
    .{ .val = 3, .str = "SO-DIMM" },
    .{ .val = 4, .str = "LRDIMM" },
    .{ .val = 5, .str = "Mini-RDIMM" },
    .{ .val = 6, .str = "Mini-UDIMM" },
    .{ .val = 7, .str = "7 - Reserved" },
    .{ .val = 8, .str = "72b-SO-RDIMM" },
    .{ .val = 9, .str = "72b-SO-UDIMM" },
    .{ .val = 10, .str = "10 - Reserved" },
    .{ .val = 11, .str = "11 - Reserved" },
    .{ .val = 12, .str = "16b-SO-DIMM" },
    .{ .val = 13, .str = "32b-SO-DIMM" },
    .{ .val = 14, .str = "14 - Reserved" },
    .{ .val = 15, .str = "No base memory present" },
    .{ .val = 0x00, .str = null },
};

pub const spd_config_vals = [_]c.struct_valstr{
    .{ .val = 0x00, .str = "None" },
    .{ .val = 0x01, .str = "Parity" },
    .{ .val = 0x02, .str = "ECC" },
    .{ .val = 0x04, .str = "Addr Cmd Parity" },
    .{ .val = 0x00, .str = null },
};

pub const spd_voltage_vals = [_]c.struct_valstr{
    .{ .val = 0x00, .str = "5.0V TTL" },
    .{ .val = 0x01, .str = "LVTTL" },
    .{ .val = 0x02, .str = "HSTL 1.5V" },
    .{ .val = 0x03, .str = "SSTL 3.3V" },
    .{ .val = 0x04, .str = "SSTL 2.5V" },
    .{ .val = 0x05, .str = "SSTL 1.8V" },
    .{ .val = 0x00, .str = null },
};

pub const jedec_id1_vals = [_]c.struct_valstr{
    .{ .val = 0x01, .str = "AMD" },
    .{ .val = 0x02, .str = "AMI" },
    .{ .val = 0x83, .str = "Fairchild" },
    .{ .val = 0x04, .str = "Fujitsu" },
    .{ .val = 0x85, .str = "GTE" },
    .{ .val = 0x86, .str = "Harris" },
    .{ .val = 0x07, .str = "Hitachi" },
    .{ .val = 0x08, .str = "Inmos" },
    .{ .val = 0x89, .str = "Intel" },
    .{ .val = 0x8A, .str = "I.T.T." },
    .{ .val = 0x0B, .str = "Intersil" },
    .{ .val = 0x8C, .str = "Monolithic Memories" },
    .{ .val = 0x0D, .str = "Mostek" },
    .{ .val = 0x0E, .str = "Freescale (Motorola)" },
    .{ .val = 0x8F, .str = "National" },
    .{ .val = 0x10, .str = "NEC" },
    .{ .val = 0x91, .str = "RCA" },
    .{ .val = 0x92, .str = "Raytheon" },
    .{ .val = 0x13, .str = "Conexant (Rockwell)" },
    .{ .val = 0x94, .str = "Seeq" },
    .{ .val = 0x15, .str = "NXP (Philips)" },
    .{ .val = 0x16, .str = "Synertek" },
    .{ .val = 0x97, .str = "Texas Instruments" },
    .{ .val = 0x98, .str = "Toshiba" },
    .{ .val = 0x19, .str = "Xicor" },
    .{ .val = 0x1A, .str = "Zilog" },
    .{ .val = 0x9B, .str = "Eurotechnique" },
    .{ .val = 0x1C, .str = "Mitsubishi" },
    .{ .val = 0x9D, .str = "Lucent (AT&T)" },
    .{ .val = 0x9E, .str = "Exel" },
    .{ .val = 0x1F, .str = "Atmel" },
    .{ .val = 0x20, .str = "STMicroelectronics" },
    .{ .val = 0xA1, .str = "Lattice Semi." },
    .{ .val = 0xA2, .str = "NCR" },
    .{ .val = 0x23, .str = "Wafer Scale Integration" },
    .{ .val = 0xA4, .str = "IBM" },
    .{ .val = 0x25, .str = "Tristar" },
    .{ .val = 0x26, .str = "Visic" },
    .{ .val = 0xA7, .str = "Intl. CMOS Technology" },
    .{ .val = 0xA8, .str = "SSSI" },
    .{ .val = 0x29, .str = "MicrochipTechnology" },
    .{ .val = 0x2A, .str = "Ricoh Ltd." },
    .{ .val = 0xAB, .str = "VLSI" },
    .{ .val = 0x2C, .str = "Micron Technology" },
    .{ .val = 0xAD, .str = "SK Hynix" },
    .{ .val = 0xAE, .str = "OKI Semiconductor" },
    .{ .val = 0x2F, .str = "ACTEL" },
    .{ .val = 0xB0, .str = "Sharp" },
    .{ .val = 0x31, .str = "Catalyst" },
    .{ .val = 0x32, .str = "Panasonic" },
    .{ .val = 0xB3, .str = "IDT" },
    .{ .val = 0x34, .str = "Cypress" },
    .{ .val = 0xB5, .str = "DEC" },
    .{ .val = 0xB6, .str = "LSI Logic" },
    .{ .val = 0x37, .str = "Zarlink (Plessey)" },
    .{ .val = 0x38, .str = "UTMC" },
    .{ .val = 0xB9, .str = "Thinking Machine" },
    .{ .val = 0xBA, .str = "Thomson CSF" },
    .{ .val = 0x3B, .str = "Integrated CMOS (Vertex)" },
    .{ .val = 0xBC, .str = "Honeywell" },
    .{ .val = 0x3D, .str = "Tektronix" },
    .{ .val = 0x3E, .str = "Oracle Corporation" },
    .{ .val = 0xBF, .str = "Silicon Storage Technology" },
    .{ .val = 0x40, .str = "ProMos/Mosel Vitelic" },
    .{ .val = 0xC1, .str = "Infineon (Siemens)" },
    .{ .val = 0xC2, .str = "Macronix" },
    .{ .val = 0x43, .str = "Xerox" },
    .{ .val = 0xC4, .str = "Plus Logic" },
    .{ .val = 0x45, .str = "SanDisk Corporation" },
    .{ .val = 0x46, .str = "Elan Circuit Tech." },
    .{ .val = 0xC7, .str = "European Silicon Str." },
    .{ .val = 0xC8, .str = "Apple Computer" },
    .{ .val = 0x49, .str = "Xilinx" },
    .{ .val = 0x4A, .str = "Compaq" },
    .{ .val = 0xCB, .str = "Protocol Engines" },
    .{ .val = 0x4C, .str = "SCI" },
    .{ .val = 0xCD, .str = "Seiko Instruments" },
    .{ .val = 0xCE, .str = "Samsung" },
    .{ .val = 0x4F, .str = "I3 Design System" },
    .{ .val = 0xD0, .str = "Klic" },
    .{ .val = 0x51, .str = "Crosspoint Solutions" },
    .{ .val = 0x52, .str = "Alliance Semiconductor" },
    .{ .val = 0xD3, .str = "Tandem" },
    .{ .val = 0x54, .str = "Hewlett-Packard" },
    .{ .val = 0xD5, .str = "Integrated Silicon Solutions" },
    .{ .val = 0xD6, .str = "Brooktree" },
    .{ .val = 0x57, .str = "New Media" },
    .{ .val = 0x58, .str = "MHS Electronic" },
    .{ .val = 0xD9, .str = "Performance Semi." },
    .{ .val = 0xDA, .str = "Winbond Electronic" },
    .{ .val = 0x5B, .str = "Kawasaki Steel" },
    .{ .val = 0xDC, .str = "Bright Micro" },
    .{ .val = 0x5D, .str = "TECMAR" },
    .{ .val = 0x5E, .str = "Exar" },
    .{ .val = 0xDF, .str = "PCMCIA" },
    .{ .val = 0xE0, .str = "LG Semi (Goldstar)" },
    .{ .val = 0x61, .str = "Northern Telecom" },
    .{ .val = 0x62, .str = "Sanyo" },
    .{ .val = 0xE3, .str = "Array Microsystems" },
    .{ .val = 0x64, .str = "Crystal Semiconductor" },
    .{ .val = 0xE5, .str = "Analog Devices" },
    .{ .val = 0xE6, .str = "PMC-Sierra" },
    .{ .val = 0x67, .str = "Asparix" },
    .{ .val = 0x68, .str = "Convex Computer" },
    .{ .val = 0xE9, .str = "Quality Semiconductor" },
    .{ .val = 0xEA, .str = "Nimbus Technology" },
    .{ .val = 0x6B, .str = "Transwitch" },
    .{ .val = 0xEC, .str = "Micronas (ITT Intermetall)" },
    .{ .val = 0x6D, .str = "Cannon" },
    .{ .val = 0x6E, .str = "Altera" },
    .{ .val = 0xEF, .str = "NEXCOM" },
    .{ .val = 0x70, .str = "Qualcomm" },
    .{ .val = 0xF1, .str = "Sony" },
    .{ .val = 0xF2, .str = "Cray Research" },
    .{ .val = 0x73, .str = "AMS(Austria Micro)" },
    .{ .val = 0xF4, .str = "Vitesse" },
    .{ .val = 0x75, .str = "Aster Electronics" },
    .{ .val = 0x76, .str = "Bay Networks (Synoptic)" },
    .{ .val = 0xF7, .str = "Zentrum/ZMD" },
    .{ .val = 0xF8, .str = "TRW" },
    .{ .val = 0x79, .str = "Thesys" },
    .{ .val = 0x7A, .str = "Solbourne Computer" },
    .{ .val = 0xFB, .str = "Allied-Signal" },
    .{ .val = 0x7C, .str = "Dialog Semiconductor" },
    .{ .val = 0xFD, .str = "Media Vision" },
    .{ .val = 0xFE, .str = "Numonyx Corporation" },
    .{ .val = 0x00, .str = null },
};

pub const jedec_id2_vals = [_]c.struct_valstr{
    .{ .val = 0x01, .str = "Cirrus Logic" },
    .{ .val = 0x02, .str = "National Instruments" },
    .{ .val = 0x83, .str = "ILC Data Device" },
    .{ .val = 0x04, .str = "Alcatel Mietec" },
    .{ .val = 0x85, .str = "Micro Linear" },
    .{ .val = 0x86, .str = "Univ. of NC" },
    .{ .val = 0x07, .str = "JTAG Technologies" },
    .{ .val = 0x08, .str = "BAE Systems (Loral)" },
    .{ .val = 0x89, .str = "Nchip" },
    .{ .val = 0x8A, .str = "Galileo Tech" },
    .{ .val = 0x0B, .str = "Bestlink Systems" },
    .{ .val = 0x8C, .str = "Graychip" },
    .{ .val = 0x0D, .str = "GENNUM" },
    .{ .val = 0x0E, .str = "VideoLogic" },
    .{ .val = 0x8F, .str = "Robert Bosch" },
    .{ .val = 0x10, .str = "Chip Express" },
    .{ .val = 0x91, .str = "DATARAM" },
    .{ .val = 0x92, .str = "United Microelectronics Corp." },
    .{ .val = 0x13, .str = "TCSI" },
    .{ .val = 0x94, .str = "Smart Modular" },
    .{ .val = 0x15, .str = "Hughes Aircraft" },
    .{ .val = 0x16, .str = "Lanstar Semiconductor" },
    .{ .val = 0x97, .str = "Qlogic" },
    .{ .val = 0x98, .str = "Kingston" },
    .{ .val = 0x19, .str = "Music Semi" },
    .{ .val = 0x1A, .str = "Ericsson Components" },
    .{ .val = 0x9B, .str = "SpaSE" },
    .{ .val = 0x1C, .str = "Eon Silicon Devices" },
    .{ .val = 0x9D, .str = "Integrated Silicon Solution (ISSI)" },
    .{ .val = 0x9E, .str = "DoD" },
    .{ .val = 0x1F, .str = "Integ. Memories Tech." },
    .{ .val = 0x20, .str = "Corollary Inc." },
    .{ .val = 0xA1, .str = "Dallas Semiconductor" },
    .{ .val = 0xA2, .str = "Omnivision" },
    .{ .val = 0x23, .str = "EIV(Switzerland)" },
    .{ .val = 0xA4, .str = "Novatel Wireless" },
    .{ .val = 0x25, .str = "Zarlink (Mitel)" },
    .{ .val = 0x26, .str = "Clearpoint" },
    .{ .val = 0xA7, .str = "Cabletron" },
    .{ .val = 0xA8, .str = "STEC (Silicon Tech)" },
    .{ .val = 0x29, .str = "Vanguard" },
    .{ .val = 0x2A, .str = "Hagiwara Sys-Com" },
    .{ .val = 0xAB, .str = "Vantis" },
    .{ .val = 0x2C, .str = "Celestica" },
    .{ .val = 0xAD, .str = "Century" },
    .{ .val = 0xAE, .str = "Hal Computers" },
    .{ .val = 0x2F, .str = "Rohm Company Ltd." },
    .{ .val = 0xB0, .str = "Juniper Networks" },
    .{ .val = 0x31, .str = "Libit Signal Processing" },
    .{ .val = 0x32, .str = "Mushkin Enhanced Memory" },
    .{ .val = 0xB3, .str = "Tundra Semiconductor" },
    .{ .val = 0x34, .str = "Adaptec Inc." },
    .{ .val = 0xB5, .str = "LightSpeed Semi." },
    .{ .val = 0xB6, .str = "ZSP Corp." },
    .{ .val = 0x37, .str = "AMIC Technology" },
    .{ .val = 0x38, .str = "Adobe Systems" },
    .{ .val = 0xB9, .str = "Dynachip" },
    .{ .val = 0xBA, .str = "PNY Technologies, Inc." },
    .{ .val = 0x3B, .str = "Newport Digital" },
    .{ .val = 0xBC, .str = "MMC Networks" },
    .{ .val = 0x3D, .str = "T Square" },
    .{ .val = 0x3E, .str = "Seiko Epson" },
    .{ .val = 0xBF, .str = "Broadcom" },
    .{ .val = 0x40, .str = "Viking Components" },
    .{ .val = 0xC1, .str = "V3 Semiconductor" },
    .{ .val = 0xC2, .str = "Flextronics (Orbit Semiconductor)" },
    .{ .val = 0x43, .str = "Suwa Electronics" },
    .{ .val = 0xC4, .str = "Transmeta" },
    .{ .val = 0x45, .str = "Micron CMS" },
    .{ .val = 0x46, .str = "American Computer & Digital Components Inc." },
    .{ .val = 0xC7, .str = "Enhance 3000 Inc." },
    .{ .val = 0xC8, .str = "Tower Semiconductor" },
    .{ .val = 0x49, .str = "CPU Design" },
    .{ .val = 0x4A, .str = "Price Point" },
    .{ .val = 0xCB, .str = "Maxim Integrated Product" },
    .{ .val = 0x4C, .str = "Tellabs" },
    .{ .val = 0xCD, .str = "Centaur Technology" },
    .{ .val = 0xCE, .str = "Unigen Corporation" },
    .{ .val = 0x4F, .str = "Transcend Information" },
    .{ .val = 0xD0, .str = "Memory Card Technology" },
    .{ .val = 0x51, .str = "CKD Corporation Ltd." },
    .{ .val = 0x52, .str = "Capital Instruments, Inc." },
    .{ .val = 0xD3, .str = "Aica Kogyo, Ltd." },
    .{ .val = 0x54, .str = "Linvex Technology" },
    .{ .val = 0xD5, .str = "MSC Vertriebs GmbH" },
    .{ .val = 0xD6, .str = "AKM Company, Ltd." },
    .{ .val = 0x57, .str = "Dynamem, Inc." },
    .{ .val = 0x58, .str = "NERA ASA" },
    .{ .val = 0xD9, .str = "GSI Technology" },
    .{ .val = 0xDA, .str = "Dane-Elec (C Memory)" },
    .{ .val = 0x5B, .str = "Acorn Computers" },
    .{ .val = 0xDC, .str = "Lara Technology" },
    .{ .val = 0x5D, .str = "Oak Technology, Inc." },
    .{ .val = 0x5E, .str = "Itec Memory" },
    .{ .val = 0xDF, .str = "Tanisys Technology" },
    .{ .val = 0xE0, .str = "Truevision" },
    .{ .val = 0x61, .str = "Wintec Industries" },
    .{ .val = 0x62, .str = "Super PC Memory" },
    .{ .val = 0xE3, .str = "MGV Memory" },
    .{ .val = 0x64, .str = "Galvantech" },
    .{ .val = 0xE5, .str = "Gadzoox Networks" },
    .{ .val = 0xE6, .str = "Multi Dimensional Cons." },
    .{ .val = 0x67, .str = "GateField" },
    .{ .val = 0x68, .str = "Integrated Memory System" },
    .{ .val = 0xE9, .str = "Triscend" },
    .{ .val = 0xEA, .str = "XaQti" },
    .{ .val = 0x6B, .str = "Goldenram" },
    .{ .val = 0xEC, .str = "Clear Logic" },
    .{ .val = 0x6D, .str = "Cimaron Communications" },
    .{ .val = 0x6E, .str = "Nippon Steel Semi. Corp." },
    .{ .val = 0xEF, .str = "Advantage Memory" },
    .{ .val = 0x70, .str = "AMCC" },
    .{ .val = 0xF1, .str = "LeCroy" },
    .{ .val = 0xF2, .str = "Yamaha Corporation" },
    .{ .val = 0x73, .str = "Digital Microwave" },
    .{ .val = 0xF4, .str = "NetLogic Microsystems" },
    .{ .val = 0x75, .str = "MIMOS Semiconductor" },
    .{ .val = 0x76, .str = "Advanced Fibre" },
    .{ .val = 0xF7, .str = "BF Goodrich Data." },
    .{ .val = 0xF8, .str = "Epigram" },
    .{ .val = 0x79, .str = "Acbel Polytech Inc." },
    .{ .val = 0x7A, .str = "Apacer Technology" },
    .{ .val = 0xFB, .str = "Admor Memory" },
    .{ .val = 0x7C, .str = "FOXCONN" },
    .{ .val = 0xFD, .str = "Quadratics Superconductor" },
    .{ .val = 0xFE, .str = "3COM" },
    .{ .val = 0x00, .str = null },
};

pub const jedec_id3_vals = [_]c.struct_valstr{
    .{ .val = 0x01, .str = "Camintonn Corporation" },
    .{ .val = 0x02, .str = "ISOA Incorporated" },
    .{ .val = 0x83, .str = "Agate Semiconductor" },
    .{ .val = 0x04, .str = "ADMtek Incorporated" },
    .{ .val = 0x85, .str = "HYPERTEC" },
    .{ .val = 0x86, .str = "Adhoc Technologies" },
    .{ .val = 0x07, .str = "MOSAID Technologies" },
    .{ .val = 0x08, .str = "Ardent Technologies" },
    .{ .val = 0x89, .str = "Switchcore" },
    .{ .val = 0x8A, .str = "Cisco Systems, Inc." },
    .{ .val = 0x0B, .str = "Allayer Technologies" },
    .{ .val = 0x8C, .str = "WorkX AG (Wichman)" },
    .{ .val = 0x0D, .str = "Oasis Semiconductor" },
    .{ .val = 0x0E, .str = "Novanet Semiconductor" },
    .{ .val = 0x8F, .str = "E-M Solutions" },
    .{ .val = 0x10, .str = "Power General" },
    .{ .val = 0x91, .str = "Advanced Hardware Arch." },
    .{ .val = 0x92, .str = "Inova Semiconductors GmbH" },
    .{ .val = 0x13, .str = "Telocity" },
    .{ .val = 0x94, .str = "Delkin Devices" },
    .{ .val = 0x15, .str = "Symagery Microsystems" },
    .{ .val = 0x16, .str = "C-Port Corporation" },
    .{ .val = 0x97, .str = "SiberCore Technologies" },
    .{ .val = 0x98, .str = "Southland Microsystems" },
    .{ .val = 0x19, .str = "Malleable Technologies" },
    .{ .val = 0x1A, .str = "Kendin Communications" },
    .{ .val = 0x9B, .str = "Great Technology Microcomputer" },
    .{ .val = 0x1C, .str = "Sanmina Corporation" },
    .{ .val = 0x9D, .str = "HADCO Corporation" },
    .{ .val = 0x9E, .str = "Corsair" },
    .{ .val = 0x1F, .str = "Actrans System Inc." },
    .{ .val = 0x20, .str = "ALPHA Technologies" },
    .{ .val = 0xA1, .str = "Silicon Laboratories, Inc. (Cygnal)" },
    .{ .val = 0xA2, .str = "Artesyn Technologies" },
    .{ .val = 0x23, .str = "Align Manufacturing" },
    .{ .val = 0xA4, .str = "Peregrine Semiconductor" },
    .{ .val = 0x25, .str = "Chameleon Systems" },
    .{ .val = 0x26, .str = "Aplus Flash Technology" },
    .{ .val = 0xA7, .str = "MIPS Technologies" },
    .{ .val = 0xA8, .str = "Chrysalis ITS" },
    .{ .val = 0x29, .str = "ADTEC Corporation" },
    .{ .val = 0x2A, .str = "Kentron Technologies" },
    .{ .val = 0xAB, .str = "Win Technologies" },
    .{ .val = 0x2C, .str = "Tezzaron Semiconductor" },
    .{ .val = 0xAD, .str = "Extreme Packet Devices" },
    .{ .val = 0xAE, .str = "RF Micro Devices" },
    .{ .val = 0x2F, .str = "Siemens AG" },
    .{ .val = 0xB0, .str = "Sarnoff Corporation" },
    .{ .val = 0x31, .str = "Itautec SA" },
    .{ .val = 0x32, .str = "Radiata Inc." },
    .{ .val = 0xB3, .str = "Benchmark Elect. (AVEX)" },
    .{ .val = 0x34, .str = "Legend" },
    .{ .val = 0xB5, .str = "SpecTek Incorporated" },
    .{ .val = 0xB6, .str = "Hi/fn" },
    .{ .val = 0x37, .str = "Enikia Incorporated" },
    .{ .val = 0x38, .str = "SwitchOn Networks" },
    .{ .val = 0xB9, .str = "AANetcom Incorporated" },
    .{ .val = 0xBA, .str = "Micro Memory Bank" },
    .{ .val = 0x3B, .str = "ESS Technology" },
    .{ .val = 0xBC, .str = "Virata Corporation" },
    .{ .val = 0x3D, .str = "Excess Bandwidth" },
    .{ .val = 0x3E, .str = "West Bay Semiconductor" },
    .{ .val = 0xBF, .str = "DSP Group" },
    .{ .val = 0x40, .str = "Newport Communications" },
    .{ .val = 0xC1, .str = "Chip2Chip Incorporated" },
    .{ .val = 0xC2, .str = "Phobos Corporation" },
    .{ .val = 0x43, .str = "Intellitech Corporation" },
    .{ .val = 0xC4, .str = "Nordic VLSI ASA" },
    .{ .val = 0x45, .str = "Ishoni Networks" },
    .{ .val = 0x46, .str = "Silicon Spice" },
    .{ .val = 0xC7, .str = "Alchemy Semiconductor" },
    .{ .val = 0xC8, .str = "Agilent Technologies" },
    .{ .val = 0x49, .str = "Centillium Communications" },
    .{ .val = 0x4A, .str = "W.L. Gore" },
    .{ .val = 0xCB, .str = "HanBit Electronics" },
    .{ .val = 0x4C, .str = "GlobeSpan" },
    .{ .val = 0xCD, .str = "Element 14" },
    .{ .val = 0xCE, .str = "Pycon" },
    .{ .val = 0x4F, .str = "Saifun Semiconductors" },
    .{ .val = 0xD0, .str = "Sibyte, Incorporated" },
    .{ .val = 0x51, .str = "MetaLink Technologies" },
    .{ .val = 0x52, .str = "Feiya Technology" },
    .{ .val = 0xD3, .str = "I & C Technology" },
    .{ .val = 0x54, .str = "Shikatronics" },
    .{ .val = 0xD5, .str = "Elektrobit" },
    .{ .val = 0xD6, .str = "Megic" },
    .{ .val = 0x57, .str = "Com-Tier" },
    .{ .val = 0x58, .str = "Malaysia Micro Solutions" },
    .{ .val = 0xD9, .str = "Hyperchip" },
    .{ .val = 0xDA, .str = "Gemstone Communications" },
    .{ .val = 0x5B, .str = "Anadigm (Anadyne)" },
    .{ .val = 0xDC, .str = "3ParData" },
    .{ .val = 0x5D, .str = "Mellanox Technologies" },
    .{ .val = 0x5E, .str = "Tenx Technologies" },
    .{ .val = 0xDF, .str = "Helix AG" },
    .{ .val = 0xE0, .str = "Domosys" },
    .{ .val = 0x61, .str = "Skyup Technology" },
    .{ .val = 0x62, .str = "HiNT Corporation" },
    .{ .val = 0xE3, .str = "Chiaro" },
    .{ .val = 0x64, .str = "MDT Technologies GmbH" },
    .{ .val = 0xE5, .str = "Exbit Technology A/S" },
    .{ .val = 0xE6, .str = "Integrated Technology Express" },
    .{ .val = 0x67, .str = "AVED Memory" },
    .{ .val = 0x68, .str = "Legerity" },
    .{ .val = 0xE9, .str = "Jasmine Networks" },
    .{ .val = 0xEA, .str = "Caspian Networks" },
    .{ .val = 0x6B, .str = "nCUBE" },
    .{ .val = 0xEC, .str = "Silicon Access Networks" },
    .{ .val = 0x6D, .str = "FDK Corporation" },
    .{ .val = 0x6E, .str = "High Bandwidth Access" },
    .{ .val = 0xEF, .str = "MultiLink Technology" },
    .{ .val = 0x70, .str = "BRECIS" },
    .{ .val = 0xF1, .str = "World Wide Packets" },
    .{ .val = 0xF2, .str = "APW" },
    .{ .val = 0x73, .str = "Chicory Systems" },
    .{ .val = 0xF4, .str = "Xstream Logic" },
    .{ .val = 0x75, .str = "Fast-Chip" },
    .{ .val = 0x76, .str = "Zucotto Wireless" },
    .{ .val = 0xF7, .str = "Realchip" },
    .{ .val = 0xF8, .str = "Galaxy Power" },
    .{ .val = 0x79, .str = "eSilicon" },
    .{ .val = 0x7A, .str = "Morphics Technology" },
    .{ .val = 0xFB, .str = "Accelerant Networks" },
    .{ .val = 0x7C, .str = "Silicon Wave" },
    .{ .val = 0xFD, .str = "SandCraft" },
    .{ .val = 0xFE, .str = "Elpida" },
    .{ .val = 0x00, .str = null },
};

pub const jedec_id4_vals = [_]c.struct_valstr{
    .{ .val = 0x01, .str = "Solectron" },
    .{ .val = 0x02, .str = "Optosys Technologies" },
    .{ .val = 0x83, .str = "Buffalo (Formerly Melco)" },
    .{ .val = 0x04, .str = "TriMedia Technologies" },
    .{ .val = 0x85, .str = "Cyan Technologies" },
    .{ .val = 0x86, .str = "Global Locate" },
    .{ .val = 0x07, .str = "Optillion" },
    .{ .val = 0x08, .str = "Terago Communications" },
    .{ .val = 0x89, .str = "Ikanos Communications" },
    .{ .val = 0x8A, .str = "Princeton Technology" },
    .{ .val = 0x0B, .str = "Nanya Technology" },
    .{ .val = 0x8C, .str = "Elite Flash Storage" },
    .{ .val = 0x0D, .str = "Mysticom" },
    .{ .val = 0x0E, .str = "LightSand Communications" },
    .{ .val = 0x8F, .str = "ATI Technologies" },
    .{ .val = 0x10, .str = "Agere Systems" },
    .{ .val = 0x91, .str = "NeoMagic" },
    .{ .val = 0x92, .str = "AuroraNetics" },
    .{ .val = 0x13, .str = "Golden Empire" },
    .{ .val = 0x94, .str = "Mushkin" },
    .{ .val = 0x15, .str = "Tioga Technologies" },
    .{ .val = 0x16, .str = "Netlist" },
    .{ .val = 0x97, .str = "TeraLogic" },
    .{ .val = 0x98, .str = "Cicada Semiconductor" },
    .{ .val = 0x19, .str = "Centon Electronics" },
    .{ .val = 0x1A, .str = "Tyco Electronics" },
    .{ .val = 0x9B, .str = "Magis Works" },
    .{ .val = 0x1C, .str = "Zettacom" },
    .{ .val = 0x9D, .str = "Cogency Semiconductor" },
    .{ .val = 0x9E, .str = "Chipcon AS" },
    .{ .val = 0x1F, .str = "Aspex Technology" },
    .{ .val = 0x20, .str = "F5 Networks" },
    .{ .val = 0xA1, .str = "Programmable Silicon Solutions" },
    .{ .val = 0xA2, .str = "ChipWrights" },
    .{ .val = 0x23, .str = "Acorn Networks" },
    .{ .val = 0xA4, .str = "Quicklogic" },
    .{ .val = 0x25, .str = "Kingmax Semiconductor" },
    .{ .val = 0x26, .str = "BOPS" },
    .{ .val = 0xA7, .str = "Flasys" },
    .{ .val = 0xA8, .str = "BitBlitz Communications" },
    .{ .val = 0x29, .str = "eMemory Technology" },
    .{ .val = 0x2A, .str = "Procket Networks" },
    .{ .val = 0xAB, .str = "Purple Ray" },
    .{ .val = 0x2C, .str = "Trebia Networks" },
    .{ .val = 0xAD, .str = "Delta Electronics" },
    .{ .val = 0xAE, .str = "Onex Communications" },
    .{ .val = 0x2F, .str = "Ample Communications" },
    .{ .val = 0xB0, .str = "Memory Experts Intl" },
    .{ .val = 0x31, .str = "Astute Networks" },
    .{ .val = 0x32, .str = "Azanda Network Devices" },
    .{ .val = 0xB3, .str = "Dibcom" },
    .{ .val = 0x34, .str = "Tekmos" },
    .{ .val = 0xB5, .str = "API NetWorks" },
    .{ .val = 0xB6, .str = "Bay Microsystems" },
    .{ .val = 0x37, .str = "Firecron Ltd" },
    .{ .val = 0x38, .str = "Resonext Communications" },
    .{ .val = 0xB9, .str = "Tachys Technologies" },
    .{ .val = 0xBA, .str = "Equator Technology" },
    .{ .val = 0x3B, .str = "Concept Computer" },
    .{ .val = 0xBC, .str = "SILCOM" },
    .{ .val = 0x3D, .str = "3Dlabs" },
    .{ .val = 0x3E, .str = "c’t Magazine" },
    .{ .val = 0xBF, .str = "Sanera Systems" },
    .{ .val = 0x40, .str = "Silicon Packets" },
    .{ .val = 0xC1, .str = "Viasystems Group" },
    .{ .val = 0xC2, .str = "Simtek" },
    .{ .val = 0x43, .str = "Semicon Devices Singapore" },
    .{ .val = 0xC4, .str = "Satron Handelsges" },
    .{ .val = 0x45, .str = "Improv Systems" },
    .{ .val = 0x46, .str = "INDUSYS GmbH" },
    .{ .val = 0xC7, .str = "Corrent" },
    .{ .val = 0xC8, .str = "Infrant Technologies" },
    .{ .val = 0x49, .str = "Ritek Corp" },
    .{ .val = 0x4A, .str = "empowerTel Networks" },
    .{ .val = 0xCB, .str = "Hypertec" },
    .{ .val = 0x4C, .str = "Cavium Networks" },
    .{ .val = 0xCD, .str = "PLX Technology" },
    .{ .val = 0xCE, .str = "Massana Design" },
    .{ .val = 0x4F, .str = "Intrinsity" },
    .{ .val = 0xD0, .str = "Valence Semiconductor" },
    .{ .val = 0x51, .str = "Terawave Communications" },
    .{ .val = 0x52, .str = "IceFyre Semiconductor" },
    .{ .val = 0xD3, .str = "Primarion" },
    .{ .val = 0x54, .str = "Picochip Designs Ltd" },
    .{ .val = 0xD5, .str = "Silverback Systems" },
    .{ .val = 0xD6, .str = "Jade Star Technologies" },
    .{ .val = 0x57, .str = "Pijnenburg Securealink" },
    .{ .val = 0x58, .str = "takeMS - Ultron AG" },
    .{ .val = 0xD9, .str = "Cambridge Silicon Radio" },
    .{ .val = 0xDA, .str = "Swissbit" },
    .{ .val = 0x5B, .str = "Nazomi Communications" },
    .{ .val = 0xDC, .str = "eWave System" },
    .{ .val = 0x5D, .str = "Rockwell Collins" },
    .{ .val = 0x5E, .str = "Picocel Co. Ltd. (Paion)" },
    .{ .val = 0xDF, .str = "Alphamosaic Ltd" },
    .{ .val = 0xE0, .str = "Sandburst" },
    .{ .val = 0x61, .str = "SiCon Video" },
    .{ .val = 0x62, .str = "NanoAmp Solutions" },
    .{ .val = 0xE3, .str = "Ericsson Technology" },
    .{ .val = 0x64, .str = "PrairieComm" },
    .{ .val = 0xE5, .str = "Mitac International" },
    .{ .val = 0xE6, .str = "Layer N Networks" },
    .{ .val = 0x67, .str = "MtekVision (Atsana)" },
    .{ .val = 0x68, .str = "Allegro Networks" },
    .{ .val = 0xE9, .str = "Marvell Semiconductors" },
    .{ .val = 0xEA, .str = "Netergy Microelectronic" },
    .{ .val = 0x6B, .str = "NVIDIA" },
    .{ .val = 0xEC, .str = "Internet Machines" },
    .{ .val = 0x6D, .str = "Memorysolution GmbH" },
    .{ .val = 0x6E, .str = "Litchfield Communication" },
    .{ .val = 0xEF, .str = "Accton Technology" },
    .{ .val = 0x70, .str = "Teradiant Networks" },
    .{ .val = 0xF1, .str = "Scaleo Chip" },
    .{ .val = 0xF2, .str = "Cortina Systems" },
    .{ .val = 0x73, .str = "RAM Components" },
    .{ .val = 0xF4, .str = "Raqia Networks" },
    .{ .val = 0x75, .str = "ClearSpeed" },
    .{ .val = 0x76, .str = "Matsushita Battery" },
    .{ .val = 0xF7, .str = "Xelerated" },
    .{ .val = 0xF8, .str = "SimpleTech" },
    .{ .val = 0x79, .str = "Utron Technology" },
    .{ .val = 0x7A, .str = "Astec International" },
    .{ .val = 0xFB, .str = "AVM gmbH" },
    .{ .val = 0x7C, .str = "Redux Communications" },
    .{ .val = 0xFD, .str = "Dot Hill Systems" },
    .{ .val = 0xFE, .str = "TeraChip" },
    .{ .val = 0x00, .str = null },
};

pub const jedec_id5_vals = [_]c.struct_valstr{
    .{ .val = 0x01, .str = "T-RAM Incorporated" },
    .{ .val = 0x02, .str = "Innovics Wireless" },
    .{ .val = 0x83, .str = "Teknovus" },
    .{ .val = 0x04, .str = "KeyEye Communications" },
    .{ .val = 0x85, .str = "Runcom Technologies" },
    .{ .val = 0x86, .str = "RedSwitch" },
    .{ .val = 0x07, .str = "Dotcast" },
    .{ .val = 0x08, .str = "Silicon Mountain Memory" },
    .{ .val = 0x89, .str = "Signia Technologies" },
    .{ .val = 0x8A, .str = "Pixim" },
    .{ .val = 0x0B, .str = "Galazar Networks" },
    .{ .val = 0x8C, .str = "White Electronic Designs" },
    .{ .val = 0x0D, .str = "Patriot Scientific" },
    .{ .val = 0x0E, .str = "Neoaxiom Corporation" },
    .{ .val = 0x8F, .str = "3Y Power Technology" },
    .{ .val = 0x10, .str = "Scaleo Chip" },
    .{ .val = 0x91, .str = "Potentia Power Systems" },
    .{ .val = 0x92, .str = "C-guys Incorporated" },
    .{ .val = 0x13, .str = "Digital Communications Technology Incorporated" },
    .{ .val = 0x94, .str = "Silicon-Based Technology" },
    .{ .val = 0x15, .str = "Fulcrum Microsystems" },
    .{ .val = 0x16, .str = "Positivo Informatica Ltd" },
    .{ .val = 0x97, .str = "XIOtech Corporation" },
    .{ .val = 0x98, .str = "PortalPlayer" },
    .{ .val = 0x19, .str = "Zhiying Software" },
    .{ .val = 0x1A, .str = "ParkerVision, Inc." },
    .{ .val = 0x9B, .str = "Phonex Broadband" },
    .{ .val = 0x1C, .str = "Skyworks Solutions" },
    .{ .val = 0x9D, .str = "Entropic Communications" },
    .{ .val = 0x9E, .str = "I’M Intelligent Memory Ltd." },
    .{ .val = 0x1F, .str = "Zensys A/S" },
    .{ .val = 0x20, .str = "Legend Silicon Corp." },
    .{ .val = 0xA1, .str = "Sci-worx GmbH" },
    .{ .val = 0xA2, .str = "SMSC (Standard Microsystems)" },
    .{ .val = 0x23, .str = "Renesas Electronics" },
    .{ .val = 0xA4, .str = "Raza Microelectronics" },
    .{ .val = 0x25, .str = "Phyworks" },
    .{ .val = 0x26, .str = "MediaTek" },
    .{ .val = 0xA7, .str = "Non-cents Productions" },
    .{ .val = 0xA8, .str = "US Modular" },
    .{ .val = 0x29, .str = "Wintegra Ltd." },
    .{ .val = 0x2A, .str = "Mathstar" },
    .{ .val = 0xAB, .str = "StarCore" },
    .{ .val = 0x2C, .str = "Oplus Technologies" },
    .{ .val = 0xAD, .str = "Mindspeed" },
    .{ .val = 0xAE, .str = "Just Young Computer" },
    .{ .val = 0x2F, .str = "Radia Communications" },
    .{ .val = 0xB0, .str = "OCZ" },
    .{ .val = 0x31, .str = "Emuzed" },
    .{ .val = 0x32, .str = "LOGIC Devices" },
    .{ .val = 0xB3, .str = "Inphi Corporation" },
    .{ .val = 0x34, .str = "Quake Technologies" },
    .{ .val = 0xB5, .str = "Vixel" },
    .{ .val = 0xB6, .str = "SolusTek" },
    .{ .val = 0x37, .str = "Kongsberg Maritime" },
    .{ .val = 0x38, .str = "Faraday Technology" },
    .{ .val = 0xB9, .str = "Altium Ltd." },
    .{ .val = 0xBA, .str = "Insyte" },
    .{ .val = 0x3B, .str = "ARM Ltd." },
    .{ .val = 0xBC, .str = "DigiVision" },
    .{ .val = 0x3D, .str = "Vativ Technologies" },
    .{ .val = 0x3E, .str = "Endicott Interconnect Technologies" },
    .{ .val = 0xBF, .str = "Pericom" },
    .{ .val = 0x40, .str = "Bandspeed" },
    .{ .val = 0xC1, .str = "LeWiz Communications" },
    .{ .val = 0xC2, .str = "CPU Technology" },
    .{ .val = 0x43, .str = "Ramaxel Technology" },
    .{ .val = 0xC4, .str = "DSP Group" },
    .{ .val = 0x45, .str = "Axis Communications" },
    .{ .val = 0x46, .str = "Legacy Electronics" },
    .{ .val = 0xC7, .str = "Chrontel" },
    .{ .val = 0xC8, .str = "Powerchip Semiconductor" },
    .{ .val = 0x49, .str = "MobilEye Technologies" },
    .{ .val = 0x4A, .str = "Excel Semiconductor" },
    .{ .val = 0xCB, .str = "A-DATA Technology" },
    .{ .val = 0x4C, .str = "VirtualDigm" },
    .{ .val = 0xCD, .str = "G Skill Intl" },
    .{ .val = 0xCE, .str = "Quanta Computer" },
    .{ .val = 0x4F, .str = "Yield Microelectronics" },
    .{ .val = 0xD0, .str = "Afa Technologies" },
    .{ .val = 0x51, .str = "KINGBOX Technology Co. Ltd." },
    .{ .val = 0x52, .str = "Ceva" },
    .{ .val = 0xD3, .str = "iStor Networks" },
    .{ .val = 0x54, .str = "Advance Modules" },
    .{ .val = 0xD5, .str = "Microsoft" },
    .{ .val = 0xD6, .str = "Open-Silicon" },
    .{ .val = 0x57, .str = "Goal Semiconductor" },
    .{ .val = 0x58, .str = "ARC International" },
    .{ .val = 0xD9, .str = "Simmtec" },
    .{ .val = 0xDA, .str = "Metanoia" },
    .{ .val = 0x5B, .str = "Key Stream" },
    .{ .val = 0xDC, .str = "Lowrance Electronics" },
    .{ .val = 0x5D, .str = "Adimos" },
    .{ .val = 0x5E, .str = "SiGe Semiconductor" },
    .{ .val = 0xDF, .str = "Fodus Communications" },
    .{ .val = 0xE0, .str = "Credence Systems Corp." },
    .{ .val = 0x61, .str = "Genesis Microchip Inc." },
    .{ .val = 0x62, .str = "Vihana, Inc." },
    .{ .val = 0xE3, .str = "WIS Technologies" },
    .{ .val = 0x64, .str = "GateChange Technologies" },
    .{ .val = 0xE5, .str = "High Density Devices AS" },
    .{ .val = 0xE6, .str = "Synopsys" },
    .{ .val = 0x67, .str = "Gigaram" },
    .{ .val = 0x68, .str = "Enigma Semiconductor Inc." },
    .{ .val = 0xE9, .str = "Century Micro Inc." },
    .{ .val = 0xEA, .str = "Icera Semiconductor" },
    .{ .val = 0x6B, .str = "Mediaworks Integrated Systems" },
    .{ .val = 0xEC, .str = "O’Neil Product Development" },
    .{ .val = 0x6D, .str = "Supreme Top Technology Ltd." },
    .{ .val = 0x6E, .str = "MicroDisplay Corporation" },
    .{ .val = 0xEF, .str = "Team Group Inc." },
    .{ .val = 0x70, .str = "Sinett Corporation" },
    .{ .val = 0xF1, .str = "Toshiba Corporation" },
    .{ .val = 0xF2, .str = "Tensilica" },
    .{ .val = 0x73, .str = "SiRF Technology" },
    .{ .val = 0xF4, .str = "Bacoc Inc." },
    .{ .val = 0x75, .str = "SMaL Camera Technologies" },
    .{ .val = 0x76, .str = "Thomson SC" },
    .{ .val = 0xF7, .str = "Airgo Networks" },
    .{ .val = 0xF8, .str = "Wisair Ltd." },
    .{ .val = 0x79, .str = "SigmaTel" },
    .{ .val = 0x7A, .str = "Arkados" },
    .{ .val = 0xFB, .str = "Compete IT gmbH Co. KG" },
    .{ .val = 0x7C, .str = "Eudar Technology Inc." },
    .{ .val = 0xFD, .str = "Focus Enhancements" },
    .{ .val = 0xFE, .str = "Xyratex" },
    .{ .val = 0x00, .str = null },
};

pub const jedec_id6_vals = [_]c.struct_valstr{
    .{ .val = 0x01, .str = "Specular Networks" },
    .{ .val = 0x02, .str = "Patriot Memory (PDP Systems)" },
    .{ .val = 0x83, .str = "U-Chip Technology Corp." },
    .{ .val = 0x04, .str = "Silicon Optix" },
    .{ .val = 0x85, .str = "Greenfield Networks" },
    .{ .val = 0x86, .str = "CompuRAM GmbH" },
    .{ .val = 0x07, .str = "Stargen, Inc." },
    .{ .val = 0x08, .str = "NetCell Corporation" },
    .{ .val = 0x89, .str = "Excalibrus Technologies Ltd" },
    .{ .val = 0x8A, .str = "SCM Microsystems" },
    .{ .val = 0x0B, .str = "Xsigo Systems, Inc." },
    .{ .val = 0x8C, .str = "CHIPS & Systems Inc" },
    .{ .val = 0x0D, .str = "Tier 1 Multichip Solutions" },
    .{ .val = 0x0E, .str = "CWRL Labs" },
    .{ .val = 0x8F, .str = "Teradici" },
    .{ .val = 0x10, .str = "Gigaram, Inc." },
    .{ .val = 0x91, .str = "g2 Microsystems" },
    .{ .val = 0x92, .str = "PowerFlash Semiconductor" },
    .{ .val = 0x13, .str = "P.A. Semi, Inc." },
    .{ .val = 0x94, .str = "NovaTech Solutions, S.A." },
    .{ .val = 0x15, .str = "c2 Microsystems, Inc." },
    .{ .val = 0x16, .str = "Level5 Networks" },
    .{ .val = 0x97, .str = "COS Memory AG" },
    .{ .val = 0x98, .str = "Innovasic Semiconductor" },
    .{ .val = 0x19, .str = "02IC Co. Ltd" },
    .{ .val = 0x1A, .str = "Tabula, Inc." },
    .{ .val = 0x9B, .str = "Crucial Technology" },
    .{ .val = 0x1C, .str = "Chelsio Communications" },
    .{ .val = 0x9D, .str = "Solarflare Communications" },
    .{ .val = 0x9E, .str = "Xambala Inc." },
    .{ .val = 0x1F, .str = "EADS Astrium" },
    .{ .val = 0x20, .str = "Terra Semiconductor, Inc." },
    .{ .val = 0xA1, .str = "Imaging Works, Inc." },
    .{ .val = 0xA2, .str = "Astute Networks, Inc." },
    .{ .val = 0x23, .str = "Tzero" },
    .{ .val = 0xA4, .str = "Emulex" },
    .{ .val = 0x25, .str = "Power-One" },
    .{ .val = 0x26, .str = "Pulse~LINK Inc." },
    .{ .val = 0xA7, .str = "Hon Hai Precision Industry" },
    .{ .val = 0xA8, .str = "White Rock Networks Inc." },
    .{ .val = 0x29, .str = "Telegent Systems USA, Inc." },
    .{ .val = 0x2A, .str = "Atrua Technologies, Inc." },
    .{ .val = 0xAB, .str = "Acbel Polytech Inc." },
    .{ .val = 0x2C, .str = "eRide Inc." },
    .{ .val = 0xAD, .str = "ULi Electronics Inc." },
    .{ .val = 0xAE, .str = "Magnum Semiconductor Inc." },
    .{ .val = 0x2F, .str = "neoOne Technology, Inc." },
    .{ .val = 0xB0, .str = "Connex Technology, Inc." },
    .{ .val = 0x31, .str = "Stream Processors, Inc." },
    .{ .val = 0x32, .str = "Focus Enhancements" },
    .{ .val = 0xB3, .str = "Telecis Wireless, Inc." },
    .{ .val = 0x34, .str = "uNav Microelectronics" },
    .{ .val = 0xB5, .str = "Tarari, Inc." },
    .{ .val = 0xB6, .str = "Ambric, Inc." },
    .{ .val = 0x37, .str = "Newport Media, Inc." },
    .{ .val = 0x38, .str = "VMTS" },
    .{ .val = 0xB9, .str = "Enuclia Semiconductor, Inc." },
    .{ .val = 0xBA, .str = "Virtium Technology Inc." },
    .{ .val = 0x3B, .str = "Solid State System Co., Ltd." },
    .{ .val = 0xBC, .str = "Kian Tech LLC" },
    .{ .val = 0x3D, .str = "Artimi" },
    .{ .val = 0x3E, .str = "Power Quotient International" },
    .{ .val = 0xBF, .str = "Avago Technologies" },
    .{ .val = 0x40, .str = "ADTechnology" },
    .{ .val = 0xC1, .str = "Sigma Designs" },
    .{ .val = 0xC2, .str = "SiCortex, Inc." },
    .{ .val = 0x43, .str = "Ventura Technology Group" },
    .{ .val = 0xC4, .str = "eASIC" },
    .{ .val = 0x45, .str = "M.H.S. SAS" },
    .{ .val = 0x46, .str = "Micro Star International" },
    .{ .val = 0xC7, .str = "Rapport Inc." },
    .{ .val = 0xC8, .str = "Makway International" },
    .{ .val = 0x49, .str = "Broad Reach Engineering Co." },
    .{ .val = 0x4A, .str = "Semiconductor Mfg Intl Corp" },
    .{ .val = 0xCB, .str = "SiConnect" },
    .{ .val = 0x4C, .str = "FCI USA Inc." },
    .{ .val = 0xCD, .str = "Validity Sensors" },
    .{ .val = 0xCE, .str = "Coney Technology Co. Ltd." },
    .{ .val = 0x4F, .str = "Spans Logic" },
    .{ .val = 0xD0, .str = "Neterion Inc." },
    .{ .val = 0x51, .str = "Qimonda" },
    .{ .val = 0x52, .str = "New Japan Radio Co. Ltd." },
    .{ .val = 0xD3, .str = "Velogix" },
    .{ .val = 0x54, .str = "Montalvo Systems" },
    .{ .val = 0xD5, .str = "iVivity Inc." },
    .{ .val = 0xD6, .str = "Walton Chaintech" },
    .{ .val = 0x57, .str = "AENEON" },
    .{ .val = 0x58, .str = "Lorom Industrial Co. Ltd." },
    .{ .val = 0xD9, .str = "Radiospire Networks" },
    .{ .val = 0xDA, .str = "Sensio Technologies, Inc." },
    .{ .val = 0x5B, .str = "Nethra Imaging" },
    .{ .val = 0xDC, .str = "Hexon Technology Pte Ltd" },
    .{ .val = 0x5D, .str = "CompuStocx (CSX)" },
    .{ .val = 0x5E, .str = "Methode Electronics, Inc." },
    .{ .val = 0xDF, .str = "Connect One Ltd." },
    .{ .val = 0xE0, .str = "Opulan Technologies" },
    .{ .val = 0x61, .str = "Septentrio NV" },
    .{ .val = 0x62, .str = "Goldenmars Technology Inc." },
    .{ .val = 0xE3, .str = "Kreton Corporation" },
    .{ .val = 0x64, .str = "Cochlear Ltd." },
    .{ .val = 0xE5, .str = "Altair Semiconductor" },
    .{ .val = 0xE6, .str = "NetEffect, Inc." },
    .{ .val = 0x67, .str = "Spansion, Inc." },
    .{ .val = 0x68, .str = "Taiwan Semiconductor Mfg" },
    .{ .val = 0xE9, .str = "Emphany Systems Inc." },
    .{ .val = 0xEA, .str = "ApaceWave Technologies" },
    .{ .val = 0x6B, .str = "Mobilygen Corporation" },
    .{ .val = 0xEC, .str = "Tego" },
    .{ .val = 0x6D, .str = "Cswitch Corporation" },
    .{ .val = 0x6E, .str = "Haier (Beijing) IC Design Co." },
    .{ .val = 0xEF, .str = "MetaRAM" },
    .{ .val = 0x70, .str = "Axel Electronics Co. Ltd." },
    .{ .val = 0xF1, .str = "Tilera Corporation" },
    .{ .val = 0xF2, .str = "Aquantia" },
    .{ .val = 0x73, .str = "Vivace Semiconductor" },
    .{ .val = 0xF4, .str = "Redpine Signals" },
    .{ .val = 0x75, .str = "Octalica" },
    .{ .val = 0x76, .str = "InterDigital Communications" },
    .{ .val = 0xF7, .str = "Avant Technology" },
    .{ .val = 0xF8, .str = "Asrock, Inc." },
    .{ .val = 0x79, .str = "Availink" },
    .{ .val = 0x7A, .str = "Quartics, Inc." },
    .{ .val = 0xFB, .str = "Element CXI" },
    .{ .val = 0x7C, .str = "Innovaciones Microelectronicas" },
    .{ .val = 0xFD, .str = "VeriSilicon Microelectronics" },
    .{ .val = 0xFE, .str = "W5 Networks" },
    .{ .val = 0x00, .str = null },
};

pub const jedec_id7_vals = [_]c.struct_valstr{
    .{ .val = 0x01, .str = "MOVEKING" },
    .{ .val = 0x02, .str = "Mavrix Technology, Inc." },
    .{ .val = 0x83, .str = "CellGuide Ltd." },
    .{ .val = 0x04, .str = "Faraday Technology" },
    .{ .val = 0x85, .str = "Diablo Technologies, Inc." },
    .{ .val = 0x86, .str = "Jennic" },
    .{ .val = 0x07, .str = "Octasic" },
    .{ .val = 0x08, .str = "Molex Incorporated" },
    .{ .val = 0x89, .str = "3Leaf Networks" },
    .{ .val = 0x8A, .str = "Bright Micron Technology" },
    .{ .val = 0x0B, .str = "Netxen" },
    .{ .val = 0x8C, .str = "NextWave Broadband Inc." },
    .{ .val = 0x0D, .str = "DisplayLink" },
    .{ .val = 0x0E, .str = "ZMOS Technology" },
    .{ .val = 0x8F, .str = "Tec-Hill" },
    .{ .val = 0x10, .str = "Multigig, Inc." },
    .{ .val = 0x91, .str = "Amimon" },
    .{ .val = 0x92, .str = "Euphonic Technologies, Inc." },
    .{ .val = 0x13, .str = "BRN Phoenix" },
    .{ .val = 0x94, .str = "InSilica" },
    .{ .val = 0x15, .str = "Ember Corporation" },
    .{ .val = 0x16, .str = "Avexir Technologies Corporation" },
    .{ .val = 0x97, .str = "Echelon Corporation" },
    .{ .val = 0x98, .str = "Edgewater Computer Systems" },
    .{ .val = 0x19, .str = "XMOS Semiconductor Ltd." },
    .{ .val = 0x1A, .str = "GENUSION, Inc." },
    .{ .val = 0x9B, .str = "Memory Corp NV" },
    .{ .val = 0x1C, .str = "SiliconBlue Technologies" },
    .{ .val = 0x9D, .str = "Rambus Inc." },
    .{ .val = 0x9E, .str = "Andes Technology Corporation" },
    .{ .val = 0x1F, .str = "Coronis Systems" },
    .{ .val = 0x20, .str = "Achronix Semiconductor" },
    .{ .val = 0xA1, .str = "Siano Mobile Silicon Ltd." },
    .{ .val = 0xA2, .str = "Semtech Corporation" },
    .{ .val = 0x23, .str = "Pixelworks Inc." },
    .{ .val = 0xA4, .str = "Gaisler Research AB" },
    .{ .val = 0x25, .str = "Teranetics" },
    .{ .val = 0x26, .str = "Toppan Printing Co. Ltd." },
    .{ .val = 0xA7, .str = "Kingxcon" },
    .{ .val = 0xA8, .str = "Silicon Integrated Systems" },
    .{ .val = 0x29, .str = "I-O Data Device, Inc." },
    .{ .val = 0x2A, .str = "NDS Americas Inc." },
    .{ .val = 0xAB, .str = "Solomon Systech Limited" },
    .{ .val = 0x2C, .str = "On Demand Microelectronics" },
    .{ .val = 0xAD, .str = "Amicus Wireless Inc." },
    .{ .val = 0xAE, .str = "SMARDTV SNC" },
    .{ .val = 0x2F, .str = "Comsys Communication Ltd." },
    .{ .val = 0xB0, .str = "Movidia Ltd." },
    .{ .val = 0x31, .str = "Javad GNSS, Inc." },
    .{ .val = 0x32, .str = "Montage Technology Group" },
    .{ .val = 0xB3, .str = "Trident Microsystems" },
    .{ .val = 0x34, .str = "Super Talent" },
    .{ .val = 0xB5, .str = "Optichron, Inc." },
    .{ .val = 0xB6, .str = "Future Waves UK Ltd." },
    .{ .val = 0x37, .str = "SiBEAM, Inc." },
    .{ .val = 0x38, .str = "Inicore,Inc." },
    .{ .val = 0xB9, .str = "Virident Systems" },
    .{ .val = 0xBA, .str = "M2000, Inc." },
    .{ .val = 0x3B, .str = "ZeroG Wireless, Inc." },
    .{ .val = 0xBC, .str = "Gingle Technology Co. Ltd." },
    .{ .val = 0x3D, .str = "Space Micro Inc." },
    .{ .val = 0x3E, .str = "Wilocity" },
    .{ .val = 0xBF, .str = "Novafora, Inc." },
    .{ .val = 0x40, .str = "iKoa Corporation" },
    .{ .val = 0xC1, .str = "ASint Technology" },
    .{ .val = 0xC2, .str = "Ramtron" },
    .{ .val = 0x43, .str = "Plato Networks Inc." },
    .{ .val = 0xC4, .str = "IPtronics AS" },
    .{ .val = 0x45, .str = "Infinite-Memories" },
    .{ .val = 0x46, .str = "Parade Technologies Inc." },
    .{ .val = 0xC7, .str = "Dune Networks" },
    .{ .val = 0xC8, .str = "GigaDevice Semiconductor" },
    .{ .val = 0x49, .str = "Modu Ltd." },
    .{ .val = 0x4A, .str = "CEITEC" },
    .{ .val = 0xCB, .str = "Northrop Grumman" },
    .{ .val = 0x4C, .str = "XRONET Corporation" },
    .{ .val = 0xCD, .str = "Sicon Semiconductor AB" },
    .{ .val = 0xCE, .str = "Atla Electronics Co. Ltd." },
    .{ .val = 0x4F, .str = "TOPRAM Technology" },
    .{ .val = 0xD0, .str = "Silego Technology Inc." },
    .{ .val = 0x51, .str = "Kinglife" },
    .{ .val = 0x52, .str = "Ability Industries Ltd." },
    .{ .val = 0xD3, .str = "Silicon Power Computer & Communications" },
    .{ .val = 0x54, .str = "Augusta Technology, Inc." },
    .{ .val = 0xD5, .str = "Nantronics Semiconductors" },
    .{ .val = 0xD6, .str = "Hilscher Gesellschaft" },
    .{ .val = 0x57, .str = "Quixant Ltd." },
    .{ .val = 0x58, .str = "Percello Ltd." },
    .{ .val = 0xD9, .str = "NextIO Inc." },
    .{ .val = 0xDA, .str = "Scanimetrics Inc." },
    .{ .val = 0x5B, .str = "FS-Semi Company Ltd." },
    .{ .val = 0xDC, .str = "Infinera Corporation" },
    .{ .val = 0x5D, .str = "SandForce Inc." },
    .{ .val = 0x5E, .str = "Lexar Media" },
    .{ .val = 0xDF, .str = "Teradyne Inc." },
    .{ .val = 0xE0, .str = "Memory Exchange Corp." },
    .{ .val = 0x61, .str = "Suzhou Smartek Electronics" },
    .{ .val = 0x62, .str = "Avantium Corporation" },
    .{ .val = 0xE3, .str = "ATP Electronics Inc." },
    .{ .val = 0x64, .str = "Valens Semiconductor Ltd" },
    .{ .val = 0xE5, .str = "Agate Logic, Inc." },
    .{ .val = 0xE6, .str = "Netronome" },
    .{ .val = 0x67, .str = "Zenverge, Inc." },
    .{ .val = 0x68, .str = "N-trig Ltd" },
    .{ .val = 0xE9, .str = "SanMax Technologies Inc." },
    .{ .val = 0xEA, .str = "Contour Semiconductor Inc." },
    .{ .val = 0x6B, .str = "TwinMOS" },
    .{ .val = 0xEC, .str = "Silicon Systems, Inc." },
    .{ .val = 0x6D, .str = "V-Color Technology Inc." },
    .{ .val = 0x6E, .str = "Certicom Corporation" },
    .{ .val = 0xEF, .str = "JSC ICC Milandr" },
    .{ .val = 0x70, .str = "PhotoFast Global Inc." },
    .{ .val = 0xF1, .str = "InnoDisk Corporation" },
    .{ .val = 0xF2, .str = "Muscle Power" },
    .{ .val = 0x73, .str = "Energy Micro" },
    .{ .val = 0xF4, .str = "Innofidei" },
    .{ .val = 0x75, .str = "CopperGate Communications" },
    .{ .val = 0x76, .str = "Holtek Semiconductor Inc." },
    .{ .val = 0xF7, .str = "Myson Century, Inc." },
    .{ .val = 0xF8, .str = "FIDELIX" },
    .{ .val = 0x79, .str = "Red Digital Cinema" },
    .{ .val = 0x7A, .str = "Densbits Technology" },
    .{ .val = 0xFB, .str = "Zempro" },
    .{ .val = 0x7C, .str = "MoSys" },
    .{ .val = 0xFD, .str = "Provigent" },
    .{ .val = 0xFE, .str = "Triad Semiconductor, Inc." },
    .{ .val = 0x00, .str = null },
};

pub const jedec_id8_vals = [_]c.struct_valstr{
    .{ .val = 0x01, .str = "Siklu Communication Ltd." },
    .{ .val = 0x02, .str = "A Force Manufacturing Ltd." },
    .{ .val = 0x83, .str = "Strontium" },
    .{ .val = 0x04, .str = "Abilis Systems" },
    .{ .val = 0x85, .str = "Siglead, Inc." },
    .{ .val = 0x86, .str = "Ubicom, Inc." },
    .{ .val = 0x07, .str = "Unifosa Corporation" },
    .{ .val = 0x08, .str = "Stretch, Inc." },
    .{ .val = 0x89, .str = "Lantiq Deutschland GmbH" },
    .{ .val = 0x8A, .str = "Visipro." },
    .{ .val = 0x0B, .str = "EKMemory" },
    .{ .val = 0x8C, .str = "Microelectronics Institute ZTE" },
    .{ .val = 0x0D, .str = "Cognovo Ltd." },
    .{ .val = 0x0E, .str = "Carry Technology Co. Ltd." },
    .{ .val = 0x8F, .str = "Nokia" },
    .{ .val = 0x10, .str = "King Tiger Technology" },
    .{ .val = 0x91, .str = "Sierra Wireless" },
    .{ .val = 0x92, .str = "HT Micron" },
    .{ .val = 0x13, .str = "Albatron Technology Co. Ltd." },
    .{ .val = 0x94, .str = "Leica Geosystems AG" },
    .{ .val = 0x15, .str = "BroadLight" },
    .{ .val = 0x16, .str = "AEXEA" },
    .{ .val = 0x97, .str = "ClariPhy Communications, Inc." },
    .{ .val = 0x98, .str = "Green Plug" },
    .{ .val = 0x19, .str = "Design Art Networks" },
    .{ .val = 0x1A, .str = "Mach Xtreme Technology Ltd." },
    .{ .val = 0x9B, .str = "ATO Solutions Co. Ltd." },
    .{ .val = 0x1C, .str = "Ramsta" },
    .{ .val = 0x9D, .str = "Greenliant Systems, Ltd." },
    .{ .val = 0x9E, .str = "Teikon" },
    .{ .val = 0x1F, .str = "Antec Hadron" },
    .{ .val = 0x20, .str = "NavCom Technology, Inc." },
    .{ .val = 0xA1, .str = "Shanghai Fudan Microelectronics" },
    .{ .val = 0xA2, .str = "Calxeda, Inc." },
    .{ .val = 0x23, .str = "JSC EDC Electronics" },
    .{ .val = 0xA4, .str = "Kandit Technology Co. Ltd." },
    .{ .val = 0x25, .str = "Ramos Technology" },
    .{ .val = 0x26, .str = "Goldenmars Technology" },
    .{ .val = 0xA7, .str = "XeL Technology Inc." },
    .{ .val = 0xA8, .str = "Newzone Corporation" },
    .{ .val = 0x29, .str = "ShenZhen MercyPower Tech" },
    .{ .val = 0x2A, .str = "Nanjing Yihuo Technology" },
    .{ .val = 0xAB, .str = "Nethra Imaging Inc." },
    .{ .val = 0x2C, .str = "SiTel Semiconductor BV" },
    .{ .val = 0xAD, .str = "SolidGear Corporation" },
    .{ .val = 0xAE, .str = "Topower Computer Ind Co Ltd." },
    .{ .val = 0x2F, .str = "Wilocity" },
    .{ .val = 0xB0, .str = "Profichip GmbH" },
    .{ .val = 0x31, .str = "Gerad Technologies" },
    .{ .val = 0x32, .str = "Ritek Corporation" },
    .{ .val = 0xB3, .str = "Gomos Technology Limited" },
    .{ .val = 0x34, .str = "Memoright Corporation" },
    .{ .val = 0xB5, .str = "D-Broad, Inc." },
    .{ .val = 0xB6, .str = "HiSilicon Technologies" },
    .{ .val = 0x37, .str = "Syndiant Inc.." },
    .{ .val = 0x38, .str = "Enverv Inc." },
    .{ .val = 0xB9, .str = "Cognex" },
    .{ .val = 0xBA, .str = "Xinnova Technology Inc." },
    .{ .val = 0x3B, .str = "Ultron AG" },
    .{ .val = 0xBC, .str = "Concord Idea Corporation" },
    .{ .val = 0x3D, .str = "AIM Corporation" },
    .{ .val = 0x3E, .str = "Lifetime Memory Products" },
    .{ .val = 0xBF, .str = "Ramsway" },
    .{ .val = 0x40, .str = "Recore Systems B.V." },
    .{ .val = 0xC1, .str = "Haotian Jinshibo Science Tech" },
    .{ .val = 0xC2, .str = "Being Advanced Memory" },
    .{ .val = 0x43, .str = "Adesto Technologies" },
    .{ .val = 0xC4, .str = "Giantec Semiconductor, Inc." },
    .{ .val = 0x45, .str = "HMD Electronics AG" },
    .{ .val = 0x46, .str = "Gloway International (HK)" },
    .{ .val = 0xC7, .str = "Kingcore" },
    .{ .val = 0xC8, .str = "Anucell Technology Holding" },
    .{ .val = 0x49, .str = "Accord Software & Systems Pvt. Ltd." },
    .{ .val = 0x4A, .str = "Active-Semi Inc." },
    .{ .val = 0xCB, .str = "Denso Corporation" },
    .{ .val = 0x4C, .str = "TLSI Inc." },
    .{ .val = 0xCD, .str = "Qidan" },
    .{ .val = 0xCE, .str = "Mustang" },
    .{ .val = 0x4F, .str = "Orca Systems" },
    .{ .val = 0xD0, .str = "Passif Semiconductor" },
    .{ .val = 0x51, .str = "GigaDevice Semiconductor (Beijing) Inc." },
    .{ .val = 0x52, .str = "Memphis Electronic" },
    .{ .val = 0xD3, .str = "Beckhoff Automation GmbH" },
    .{ .val = 0x54, .str = "Harmony Semiconductor Corp" },
    .{ .val = 0xD5, .str = "Air Computers SRL" },
    .{ .val = 0xD6, .str = "TMT Memory" },
    .{ .val = 0x57, .str = "Eorex Corporation" },
    .{ .val = 0x58, .str = "Xingtera" },
    .{ .val = 0xD9, .str = "Netsol" },
    .{ .val = 0xDA, .str = "Bestdon Technology Co. Ltd." },
    .{ .val = 0x5B, .str = "Baysand Inc." },
    .{ .val = 0xDC, .str = "Uroad Technology Co. Ltd." },
    .{ .val = 0x5D, .str = "Wilk Elektronik S.A." },
    .{ .val = 0x5E, .str = "AAI" },
    .{ .val = 0xDF, .str = "Harman" },
    .{ .val = 0xE0, .str = "Berg Microelectronics Inc." },
    .{ .val = 0x61, .str = "ASSIA, Inc." },
    .{ .val = 0x62, .str = "Visiontek Products LLC" },
    .{ .val = 0xE3, .str = "OCMEMORY" },
    .{ .val = 0x64, .str = "Welink Solution Inc." },
    .{ .val = 0xE5, .str = "Shark Gaming" },
    .{ .val = 0xE6, .str = "Avalanche Technology" },
    .{ .val = 0x67, .str = "R&D Center ELVEES OJSC" },
    .{ .val = 0x68, .str = "KingboMars Technology Co. Ltd." },
    .{ .val = 0xE9, .str = "High Bridge Solutions Industria Eletronica" },
    .{ .val = 0xEA, .str = "Transcend Technology Co. Ltd." },
    .{ .val = 0x6B, .str = "Everspin Technologies" },
    .{ .val = 0xEC, .str = "Hon-Hai Precision" },
    .{ .val = 0x6D, .str = "Smart Storage Systems" },
    .{ .val = 0x6E, .str = "Toumaz Group" },
    .{ .val = 0xEF, .str = "Zentel Electronics Corporation" },
    .{ .val = 0x70, .str = "Panram International Corporation" },
    .{ .val = 0xF1, .str = "Silicon Space Technology" },
    .{ .val = 0xF2, .str = "LITE-ON IT Corporation" },
    .{ .val = 0x73, .str = "Inuitive" },
    .{ .val = 0xF4, .str = "HMicro" },
    .{ .val = 0x75, .str = "BittWare, Inc." },
    .{ .val = 0x76, .str = "GLOBALFOUNDRIES" },
    .{ .val = 0xF7, .str = "ACPI Digital Co. Ltd." },
    .{ .val = 0xF8, .str = "Annapurna Labs" },
    .{ .val = 0x79, .str = "AcSiP Technology Corporation" },
    .{ .val = 0x7A, .str = "Idea! Electronic Systems" },
    .{ .val = 0xFB, .str = "Gowe Technology Co. Ltd." },
    .{ .val = 0x7C, .str = "Hermes Testing Solutions, Inc." },
    .{ .val = 0xFD, .str = "Positivo BGH" },
    .{ .val = 0xFE, .str = "Intelligence Silicon Technology" },
    .{ .val = 0x00, .str = null },
};

pub const jedec_id9_vals = [_]c.struct_valstr{
    .{ .val = 0x01, .str = "3D PLUS" },
    .{ .val = 0x02, .str = "Diehl Aerospace" },
    .{ .val = 0x83, .str = "Fairchild" },
    .{ .val = 0x04, .str = "Mercury Systems" },
    .{ .val = 0x85, .str = "Sonics, Inc." },
    .{ .val = 0x86, .str = "GE Intelligent Platforms GmbH & Co." },
    .{ .val = 0x07, .str = "Shenzhen Jinge Information Co. Ltd." },
    .{ .val = 0x08, .str = "SCWW" },
    .{ .val = 0x89, .str = "Silicon Motion Inc." },
    .{ .val = 0x8A, .str = "Anurag" },
    .{ .val = 0x0B, .str = "King Kong" },
    .{ .val = 0x8C, .str = "FROM30 Co. Ltd." },
    .{ .val = 0x0D, .str = "Gowin Semiconductor Corp" },
    .{ .val = 0x0E, .str = "Fremont Micro Devices Ltd." },
    .{ .val = 0x8F, .str = "Ericsson Modems" },
    .{ .val = 0x10, .str = "Exelis" },
    .{ .val = 0x91, .str = "Satixfy Ltd." },
    .{ .val = 0x92, .str = "Galaxy Microsystems Ltd." },
    .{ .val = 0x13, .str = "Gloway International Co. Ltd." },
    .{ .val = 0x94, .str = "Lab" },
    .{ .val = 0x15, .str = "Smart Energy Instruments" },
    .{ .val = 0x16, .str = "Approved Memory Corporation" },
    .{ .val = 0x97, .str = "Axell Corporation" },
    .{ .val = 0x98, .str = "Essencore Limited" },
    .{ .val = 0x19, .str = "Phytium" },
    .{ .val = 0x1A, .str = "Xi’an SinoChip Semiconductor" },
    .{ .val = 0x9B, .str = "Ambiq Micro" },
    .{ .val = 0x1C, .str = "eveRAM Technology, Inc." },
    .{ .val = 0x9D, .str = "Infomax" },
    .{ .val = 0x9E, .str = "Butterfly Network, Inc." },
    .{ .val = 0x1F, .str = "Shenzhen City Gcai Electronics" },
    .{ .val = 0x20, .str = "Stack Devices Corporation" },
    .{ .val = 0xA1, .str = "ADK Media Group" },
    .{ .val = 0xA2, .str = "TSP Global Co., Ltd." },
    .{ .val = 0x23, .str = "HighX" },
    .{ .val = 0xA4, .str = "Shenzhen Elicks Technology" },
    .{ .val = 0x25, .str = "ISSI/Chingis" },
    .{ .val = 0x26, .str = "Google, Inc." },
    .{ .val = 0xA7, .str = "Dasima International Development" },
    .{ .val = 0xA8, .str = "Leahkinn Technology Limited" },
    .{ .val = 0x29, .str = "HIMA Paul Hildebrandt GmbH Co KG" },
    .{ .val = 0x2A, .str = "Keysight Technologies" },
    .{ .val = 0xAB, .str = "Techcomp International (Fastable)" },
    .{ .val = 0x2C, .str = "Ancore Technology Corporation" },
    .{ .val = 0xAD, .str = "Nuvoton" },
    .{ .val = 0xAE, .str = "Korea Uhbele International Group Ltd." },
    .{ .val = 0x2F, .str = "Ikegami Tsushinki Co Ltd." },
    .{ .val = 0xB0, .str = "RelChip, Inc." },
    .{ .val = 0x31, .str = "Baikal Electronics" },
    .{ .val = 0x32, .str = "Nemostech Inc." },
    .{ .val = 0xB3, .str = "Memorysolution GmbH" },
    .{ .val = 0x34, .str = "Silicon Integrated Systems Corporation" },
    .{ .val = 0xB5, .str = "Xiede" },
    .{ .val = 0xB6, .str = "Multilaser Components" },
    .{ .val = 0x37, .str = "Flash Chi" },
    .{ .val = 0x38, .str = "Jone" },
    .{ .val = 0xB9, .str = "GCT Semiconductor Inc." },
    .{ .val = 0xBA, .str = "Hong Kong Zetta Device Technology" },
    .{ .val = 0x3B, .str = "Unimemory Technology(s) Pte Ltd." },
    .{ .val = 0xBC, .str = "Cuso" },
    .{ .val = 0x3D, .str = "Kuso" },
    .{ .val = 0x3E, .str = "Uniquify Inc." },
    .{ .val = 0xBF, .str = "Skymedi Corporation" },
    .{ .val = 0x40, .str = "Core Chance Co. Ltd." },
    .{ .val = 0xC1, .str = "Tekism Co. Ltd." },
    .{ .val = 0xC2, .str = "Seagate Technology PLC" },
    .{ .val = 0x43, .str = "Hong Kong Gaia Group Co. Limited" },
    .{ .val = 0xC4, .str = "Gigacom Semiconductor LLC" },
    .{ .val = 0x45, .str = "V2 Technologies" },
    .{ .val = 0x46, .str = "TLi" },
    .{ .val = 0xC7, .str = "Neotion" },
    .{ .val = 0xC8, .str = "Lenovo" },
    .{ .val = 0x49, .str = "Shenzhen Zhongteng Electronic Corp. Ltd." },
    .{ .val = 0x4A, .str = "Compound Photonics" },
    .{ .val = 0xCB, .str = "in2H2 inc" },
    .{ .val = 0x4C, .str = "Shenzhen Pango Microsystems Co. Ltd" },
    .{ .val = 0xCD, .str = "Vasekey" },
    .{ .val = 0xCE, .str = "Cal-Comp Industria de Semicondutores" },
    .{ .val = 0x4F, .str = "Eyenix Co., Ltd." },
    .{ .val = 0xD0, .str = "Heoriady" },
    .{ .val = 0x51, .str = "Accelerated Memory Production Inc." },
    .{ .val = 0x52, .str = "INVECAS, Inc." },
    .{ .val = 0xD3, .str = "AP Memory" },
    .{ .val = 0x54, .str = "Douqi Technology" },
    .{ .val = 0xD5, .str = "Etron Technology, Inc." },
    .{ .val = 0xD6, .str = "Indie Semiconductor" },
    .{ .val = 0x57, .str = "Socionext Inc." },
    .{ .val = 0x58, .str = "HGST" },
    .{ .val = 0xD9, .str = "EVGA" },
    .{ .val = 0xDA, .str = "Audience Inc." },
    .{ .val = 0x5B, .str = "EpicGear" },
    .{ .val = 0xDC, .str = "Vitesse Enterprise Co." },
    .{ .val = 0x5D, .str = "Foxtronn International Corporation" },
    .{ .val = 0x5E, .str = "Bretelon Inc." },
    .{ .val = 0xDF, .str = "Zbit Semiconductor, Inc." },
    .{ .val = 0xE0, .str = "Eoplex Inc" },
    .{ .val = 0x61, .str = "MaxLinear, Inc." },
    .{ .val = 0x62, .str = "ETA Devices" },
    .{ .val = 0xE3, .str = "LOKI" },
    .{ .val = 0x64, .str = "IMS Semiconductor Co., Ltd" },
    .{ .val = 0xE5, .str = "Dosilicon Co., Ltd." },
    .{ .val = 0xE6, .str = "Dolphin Integration" },
    .{ .val = 0x67, .str = "Shenzhen Mic Electronics Technology" },
    .{ .val = 0x68, .str = "Boya Microelectronics Inc." },
    .{ .val = 0xE9, .str = "Geniachip (Roche)" },
    .{ .val = 0xEA, .str = "Axign" },
    .{ .val = 0x6B, .str = "Kingred Electronic Technology Ltd." },
    .{ .val = 0xEC, .str = "Chao Yue Zhuo Computer Business Dept." },
    .{ .val = 0x6D, .str = "Guangzhou Si Nuo Electronic Technology." },
    .{ .val = 0x00, .str = null },
};

pub fn exportSymbols() void {
    comptime {
        @export(&spd_memtype_vals, .{ .name = "spd_memtype_vals", .linkage = .strong });
        @export(&ddr3_density_vals, .{ .name = "ddr3_density_vals", .linkage = .strong });
        @export(&ddr3_banks_vals, .{ .name = "ddr3_banks_vals", .linkage = .strong });
        @export(&ddr3_ecc_vals, .{ .name = "ddr3_ecc_vals", .linkage = .strong });
        @export(&ddr4_density_vals, .{ .name = "ddr4_density_vals", .linkage = .strong });
        @export(&ddr4_banks_vals, .{ .name = "ddr4_banks_vals", .linkage = .strong });
        @export(&ddr4_bank_groups, .{ .name = "ddr4_bank_groups", .linkage = .strong });
        @export(&ddr4_package_type, .{ .name = "ddr4_package_type", .linkage = .strong });
        @export(&ddr4_technology_type, .{ .name = "ddr4_technology_type", .linkage = .strong });
        @export(&spd_config_vals, .{ .name = "spd_config_vals", .linkage = .strong });
        @export(&spd_voltage_vals, .{ .name = "spd_voltage_vals", .linkage = .strong });
        @export(&jedec_id1_vals, .{ .name = "jedec_id1_vals", .linkage = .strong });
        @export(&jedec_id2_vals, .{ .name = "jedec_id2_vals", .linkage = .strong });
        @export(&jedec_id3_vals, .{ .name = "jedec_id3_vals", .linkage = .strong });
        @export(&jedec_id4_vals, .{ .name = "jedec_id4_vals", .linkage = .strong });
        @export(&jedec_id5_vals, .{ .name = "jedec_id5_vals", .linkage = .strong });
        @export(&jedec_id6_vals, .{ .name = "jedec_id6_vals", .linkage = .strong });
        @export(&jedec_id7_vals, .{ .name = "jedec_id7_vals", .linkage = .strong });
        @export(&jedec_id8_vals, .{ .name = "jedec_id8_vals", .linkage = .strong });
        @export(&jedec_id9_vals, .{ .name = "jedec_id9_vals", .linkage = .strong });
    }
}
