"""Generate deterministic FWUM images for C/Zig golden tests.

The FWUM metadata starts at byte 0x5a0.  Unlike HPM, the C command checks
neither a magic value, advertised file size, nor the embedded checksum.
"""

from pathlib import Path

ROOT = Path(__file__).resolve().parent
SIZE = 0x4000
OFFSET = 0x5A0


def write(name: str, image: bytearray) -> None:
    lines = [
        "# Generated by tests/fixtures/fwum/generate.py; input to the golden harness.",
        *(
            " ".join(f"{byte:02x}" for byte in image[index : index + 16])
            for index in range(0, len(image), 16)
        ),
    ]
    (ROOT / f"{name}.hex").write_text("\n".join(lines) + "\n")


image = bytearray((index * 37 + 13) % 256 for index in range(SIZE))
image[OFFSET : OFFSET + 17] = bytes.fromhex(
    "00 00 40 00 00 00 13 8a 20 01 02 07 42 09 98 3a 00"
)
# Two-byte big-endian additive checksum, including the checksum field itself.
checksum = -sum(image) & 0xFFFF
image[OFFSET + 4 : OFFSET + 6] = checksum.to_bytes(2, "big")
write("valid", image)
