/*
 * Crypto parity vector generator.
 *
 * This links the *original OpenSSL-backed C* crypto sources -- `md5.c`,
 * `auth.c`, `lanplus_crypt_impl.c` and `lanplus_crypt.c` -- and dumps every
 * input/output pair the Zig `std.crypto` ports have to reproduce bit for bit.
 * The fixtures it writes live in `tests/crypto/vectors/` and are the reference
 * the Zig unit tests in `src/zig/crypto/vectors_test.zig` assert against.
 *
 *     zig build gen-crypto-vectors      # regenerates tests/crypto/vectors/
 *
 * It is deliberately not part of `zig build` or `zig build test`: it is the
 * only thing left in the tree that needs libcrypto, and it exists so the
 * vectors can be re-derived from the C at any point during the migration.
 *
 * The RAKP intermediates (the exact bytes hashed for RAKP 2/3/4, the SIK and
 * K1/K2) are not returned by the C functions, so they are captured through the
 * `printbuf()` calls the C already makes at `verbose > 2`: this file provides
 * its own `printbuf` that records the buffers instead of printing them.  That
 * way the vectors are the real intermediate state of the C implementation
 * rather than a second-guess of it.
 */

#if defined(HAVE_CONFIG_H)
# include <config.h>
#endif

#include <stdarg.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include <ipmitool/ipmi.h>
#include <ipmitool/ipmi_constants.h>
#include <ipmitool/ipmi_intf.h>

#include "../../src/plugins/lan/md5.h"
#include "../../src/plugins/lan/auth.h"
#include "../../src/plugins/lanplus/lanplus.h"
#include "../../src/plugins/lanplus/lanplus_crypt.h"
#include "../../src/plugins/lanplus/lanplus_crypt_impl.h"

/* ------------------------------------------------------------------ */
/* Stubs for the rest of ipmitool                                       */
/* ------------------------------------------------------------------ */

int verbose = 4;
int csv_output = 0;

static const char *active_oem = NULL;

int ipmi_oem_active(struct ipmi_intf *intf, const char *oemtype)
{
	(void)intf;
	return active_oem && !strcmp(active_oem, oemtype);
}

void lprintf(int level, const char *format, ...)
{
	(void)level;
	(void)format;
}

const char *buf2str_extended(const uint8_t *buf, int len, const char *sep);
const char *buf2str(const uint8_t *buf, int len);

const char *buf2str_extended(const uint8_t *buf, int len, const char *sep)
{
	static char str[2048];
	int i, n = 0;

	(void)sep;
	str[0] = 0;
	for (i = 0; i < len && n < (int)sizeof(str) - 3; ++i)
		n += sprintf(str + n, "%02x", buf[i]);
	return str;
}

const char *buf2str(const uint8_t *buf, int len)
{
	return buf2str_extended(buf, len, NULL);
}

/* ------------------------------------------------------------------ */
/* printbuf capture                                                     */
/* ------------------------------------------------------------------ */

#define CAPTURE_MAX      16
#define CAPTURE_BUF_MAX 512

static struct {
	char desc[128];
	uint8_t buf[CAPTURE_BUF_MAX];
	int len;
} captures[CAPTURE_MAX];
static int capture_count;

void printbuf(const uint8_t *buf, int len, const char *desc)
{
	if (capture_count >= CAPTURE_MAX || len > CAPTURE_BUF_MAX)
		return;
	snprintf(captures[capture_count].desc,
	         sizeof(captures[capture_count].desc), "%s", desc);
	memcpy(captures[capture_count].buf, buf, len);
	captures[capture_count].len = len;
	++capture_count;
}

static void capture_reset(void)
{
	capture_count = 0;
}

static const uint8_t *capture_get(const char *desc, int *len)
{
	int i;
	for (i = 0; i < capture_count; ++i) {
		if (!strcmp(captures[i].desc, desc)) {
			*len = captures[i].len;
			return captures[i].buf;
		}
	}
	fprintf(stderr, "gen_vectors: no printbuf capture for \"%s\"\n", desc);
	exit(1);
}

/* ------------------------------------------------------------------ */
/* Output helpers: an INI-ish record format, one hex field per line     */
/* ------------------------------------------------------------------ */

static FILE *out;

static void emit_header(const char *what)
{
	fprintf(out,
	        "# %s\n"
	        "#\n"
	        "# Generated by tests/crypto/gen_vectors.c from the OpenSSL-backed C\n"
	        "# implementation.  Do not edit by hand; run `zig build gen-crypto-vectors`.\n",
	        what);
}

static void emit_case(const char *name)
{
	fprintf(out, "\n[%s]\n", name);
}

static void emit_hex(const char *field, const uint8_t *buf, int len)
{
	int i;
	fprintf(out, "%s=", field);
	for (i = 0; i < len; ++i)
		fprintf(out, "%02x", buf[i]);
	fprintf(out, "\n");
}

static void emit_int(const char *field, long value)
{
	fprintf(out, "%s=%ld\n", field, value);
}

static void emit_str(const char *field, const char *value)
{
	fprintf(out, "%s=%s\n", field, value);
}

static void emit_capture(const char *field, const char *desc)
{
	int len;
	const uint8_t *buf = capture_get(desc, &len);
	emit_hex(field, buf, len);
}

static void open_out(const char *dir, const char *name, const char *what)
{
	char path[1024];
	snprintf(path, sizeof(path), "%s/%s", dir, name);
	out = fopen(path, "w");
	if (!out) {
		fprintf(stderr, "gen_vectors: cannot write %s\n", path);
		exit(1);
	}
	emit_header(what);
}

static void close_out(void)
{
	fclose(out);
	out = NULL;
}

/* Deterministic filler so a regenerated fixture only changes when the C does. */
static void fill(uint8_t *buf, int len, int seed)
{
	int i;
	for (i = 0; i < len; ++i)
		buf[i] = (uint8_t)((i * 7 + seed * 31 + 0x5a) & 0xff);
}

/* ------------------------------------------------------------------ */
/* md5.c: the bundled MD5                                               */
/* ------------------------------------------------------------------ */

static void gen_md5(const char *dir)
{
	static const char *messages[] = {
		"",
		"a",
		"abc",
		"message digest",
		"abcdefghijklmnopqrstuvwxyz",
		"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789",
		"1234567890123456789012345678901234567890"
		"1234567890123456789012345678901234567890",
	};
	uint8_t big[1000];
	md5_state_t state;
	md5_byte_t digest[16];
	size_t i;
	int chunk;

	open_out(dir, "md5.txt", "Bundled MD5 (src/plugins/lan/md5.c)");

	for (i = 0; i < sizeof(messages) / sizeof(messages[0]); ++i) {
		char name[64];
		snprintf(name, sizeof(name), "md5/rfc1321/%zu", i);
		emit_case(name);
		md5_init(&state);
		md5_append(&state, (const md5_byte_t *)messages[i],
		           (int)strlen(messages[i]));
		md5_finish(&state, digest);
		emit_hex("input", (const uint8_t *)messages[i],
		         (int)strlen(messages[i]));
		emit_hex("digest", digest, 16);
	}

	/* Lengths straddling the 64 byte block and the 56 byte length field. */
	fill(big, sizeof(big), 3);
	{
		static const int lengths[] = {
			1, 55, 56, 57, 63, 64, 65, 119, 120, 121, 128, 191, 1000
		};
		for (i = 0; i < sizeof(lengths) / sizeof(lengths[0]); ++i) {
			char name[64];
			snprintf(name, sizeof(name), "md5/len/%d", lengths[i]);
			emit_case(name);
			md5_init(&state);
			md5_append(&state, big, lengths[i]);
			md5_finish(&state, digest);
			emit_hex("input", big, lengths[i]);
			emit_hex("digest", digest, 16);
		}
	}

	/* Streaming: the same 200 bytes fed in fixed size chunks. */
	for (chunk = 1; chunk <= 64; chunk *= 2) {
		char name[64];
		int offset = 0;
		snprintf(name, sizeof(name), "md5/stream/%d", chunk);
		emit_case(name);
		md5_init(&state);
		while (offset < 200) {
			int n = (200 - offset < chunk) ? 200 - offset : chunk;
			md5_append(&state, big + offset, n);
			offset += n;
		}
		md5_finish(&state, digest);
		emit_hex("input", big, 200);
		emit_int("chunk", chunk);
		emit_hex("digest", digest, 16);
	}

	/* md5_append with a non-positive length is a documented no-op. */
	emit_case("md5/append-zero");
	md5_init(&state);
	md5_append(&state, big, 0);
	md5_append(&state, big, 16);
	md5_append(&state, big, -1);
	md5_finish(&state, digest);
	emit_hex("input", big, 16);
	emit_hex("digest", digest, 16);

	close_out();
}

/* ------------------------------------------------------------------ */
/* auth.c: IPMI v1.5 per-message authentication                         */
/* ------------------------------------------------------------------ */

static void gen_auth(const char *dir)
{
	struct ipmi_session session;
	uint8_t data[128];
	uint8_t *md;
	int i;

	open_out(dir, "auth.txt", "IPMI v1.5 auth codes (src/plugins/lan/auth.c)");

	for (i = 0; i < 4; ++i) {
		char name[64];
		int data_len = (int)(i * 23);

		memset(&session, 0, sizeof(session));
		fill(session.authcode, 16, i + 1);
		session.session_id = 0xa1b2c3d4u + (uint32_t)i;
		session.in_seq = 0x01020304u + (uint32_t)i;
		fill(data, sizeof(data), i + 9);

		snprintf(name, sizeof(name), "auth/md5/%d", i);
		emit_case(name);
		emit_hex("authcode", session.authcode, 16);
		emit_hex("session_id", (const uint8_t *)&session.session_id, 4);
		emit_hex("in_seq", (const uint8_t *)&session.in_seq, 4);
		emit_hex("data", data, data_len);
		md = ipmi_auth_md5(&session, data, data_len);
		emit_hex("authcode_out", md, 16);
	}

	for (i = 0; i < 3; ++i) {
		char name[64];
		static const char *passwords[] = { "", "password", "0123456789abcdefghij" };

		memset(&session, 0, sizeof(session));
		snprintf((char *)session.authcode, sizeof(session.authcode), "%s",
		         passwords[i]);
		fill(session.challenge, 16, i + 5);

		snprintf(name, sizeof(name), "auth/special/%d", i);
		emit_case(name);
		emit_hex("authcode", session.authcode, 21);
		emit_hex("challenge", session.challenge, 16);
		md = ipmi_auth_special(&session);
		emit_hex("authcode_out", md, 16);
	}

	/*
	 * MD2 was removed from OpenSSL 3, so HAVE_CRYPTO_MD2 is never defined and
	 * this is the only behaviour the baseline can produce: sixteen zero bytes
	 * plus a warning on stdout.  Recorded so the Zig port cannot drift.
	 */
	memset(&session, 0, sizeof(session));
	fill(session.authcode, 16, 2);
	fill(data, sizeof(data), 4);
	emit_case("auth/md2/unsupported");
	emit_hex("authcode", session.authcode, 16);
	emit_hex("data", data, 32);
	md = ipmi_auth_md2(&session, data, 32);
	emit_hex("authcode_out", md, 16);

	close_out();
}

/* ------------------------------------------------------------------ */
/* lanplus_crypt_impl.c: HMAC and AES-128-CBC                           */
/* ------------------------------------------------------------------ */

static void gen_hmac(const char *dir)
{
	static const uint8_t macs[] = {
		IPMI_AUTH_RAKP_HMAC_SHA1,       /* == IPMI_INTEGRITY_HMAC_SHA1_96    */
		IPMI_AUTH_RAKP_HMAC_MD5,        /* == IPMI_INTEGRITY_HMAC_MD5_128    */
		IPMI_AUTH_RAKP_HMAC_SHA256,     /* == IPMI_INTEGRITY_MD5_128         */
		IPMI_INTEGRITY_HMAC_SHA256_128,
	};
	/* Key lengths straddle every hash block size (64 bytes) so that the
	 * "key longer than the block" folding path is covered for all three. */
	static const int key_lens[] = { 0, 1, 16, 20, 32, 63, 64, 65, 100, 128 };
	static const int data_lens[] = { 0, 1, 16, 20, 55, 64, 65, 200 };
	uint8_t key[128];
	uint8_t data[200];
	uint8_t md[IPMI_MAX_MD_SIZE];
	uint32_t md_len;
	size_t m, k, d;

	open_out(dir, "hmac.txt", "lanplus_HMAC (src/plugins/lanplus/lanplus_crypt_impl.c)");

	for (m = 0; m < sizeof(macs) / sizeof(macs[0]); ++m) {
		for (k = 0; k < sizeof(key_lens) / sizeof(key_lens[0]); ++k) {
			for (d = 0; d < sizeof(data_lens) / sizeof(data_lens[0]); ++d) {
				char name[64];
				snprintf(name, sizeof(name), "hmac/%02x/%d/%d",
				         macs[m], key_lens[k], data_lens[d]);
				fill(key, key_lens[k], (int)(k + 1));
				fill(data, data_lens[d], (int)(d + 11));
				memset(md, 0, sizeof(md));
				md_len = 0;
				lanplus_HMAC(macs[m], key, key_lens[k], data,
				             data_lens[d], md, &md_len);
				emit_case(name);
				emit_int("mac", macs[m]);
				emit_hex("key", key, key_lens[k]);
				emit_hex("data", data, data_lens[d]);
				emit_int("md_len", md_len);
				emit_hex("md", md, (int)md_len);
			}
		}
	}

	close_out();
}

static void gen_aes(const char *dir)
{
	static const int lengths[] = { 0, 16, 32, 48, 64, 80, 160, 512 };
	uint8_t iv[16];
	uint8_t key[16];
	uint8_t input[512];
	uint8_t output[512 + 32];
	uint8_t roundtrip[512 + 32];
	uint32_t written, back;
	size_t i;

	open_out(dir, "aes_cbc.txt",
	         "lanplus_{en,de}crypt_aes_cbc_128 (src/plugins/lanplus/lanplus_crypt_impl.c)");

	for (i = 0; i < sizeof(lengths) / sizeof(lengths[0]); ++i) {
		char name[64];
		int len = lengths[i];

		fill(iv, 16, (int)i + 1);
		fill(key, 16, (int)i + 21);
		fill(input, len, (int)i + 41);
		memset(output, 0xcc, sizeof(output));
		written = 0xdeadbeef;
		lanplus_encrypt_aes_cbc_128(iv, key, input, len, output, &written);

		snprintf(name, sizeof(name), "aes/encrypt/%d", len);
		emit_case(name);
		emit_hex("iv", iv, 16);
		emit_hex("key", key, 16);
		emit_hex("input", input, len);
		emit_int("bytes_written", written);
		emit_hex("output", output, (int)written);

		memset(roundtrip, 0xcc, sizeof(roundtrip));
		back = 0xdeadbeef;
		lanplus_decrypt_aes_cbc_128(iv, key, output, written, roundtrip, &back);

		snprintf(name, sizeof(name), "aes/decrypt/%d", len);
		emit_case(name);
		emit_hex("iv", iv, 16);
		emit_hex("key", key, 16);
		emit_hex("input", output, (int)written);
		emit_int("bytes_written", back);
		emit_hex("output", roundtrip, (int)back);
	}

	/* In-place encryption: the RMCP+ path hands overlapping buffers around. */
	fill(iv, 16, 77);
	fill(key, 16, 78);
	fill(input, 64, 79);
	memcpy(output, input, 64);
	written = 0;
	lanplus_encrypt_aes_cbc_128(iv, key, output, 64, output, &written);
	emit_case("aes/encrypt-in-place/64");
	emit_hex("iv", iv, 16);
	emit_hex("key", key, 16);
	emit_hex("input", input, 64);
	emit_int("bytes_written", written);
	emit_hex("output", output, (int)written);

	close_out();
}

/* ------------------------------------------------------------------ */
/* lanplus_crypt.c: confidentiality payloads                            */
/* ------------------------------------------------------------------ */

static void gen_payload(const char *dir)
{
	static const int lengths[] = {
		0, 1, 2, 13, 14, 15, 16, 17, 30, 31, 32, 33, 47, 100, 255
	};
	uint8_t key[16];
	uint8_t input[512];
	uint8_t output[1024];
	uint8_t decoded[1024];
	uint16_t written, size;
	size_t i;

	open_out(dir, "payload.txt",
	         "lanplus_{en,de}crypt_payload (src/plugins/lanplus/lanplus_crypt.c)");

	for (i = 0; i < sizeof(lengths) / sizeof(lengths[0]); ++i) {
		char name[64];
		int len = lengths[i];

		fill(key, 16, (int)i + 61);
		fill(input, len, (int)i + 81);
		memset(output, 0xcc, sizeof(output));
		written = 0;
		capture_reset();
		if (lanplus_encrypt_payload(IPMI_CRYPT_AES_CBC_128, key, input, len,
		                            output, &written)) {
			fprintf(stderr, "gen_vectors: encrypt_payload failed\n");
			exit(1);
		}

		snprintf(name, sizeof(name), "payload/aes/%d", len);
		emit_case(name);
		emit_hex("key", key, 16);
		emit_hex("input", input, len);
		/* The IV is generated inside the call; it is the first block of
		 * the output and is recorded so the vector stays reproducible. */
		emit_capture("iv", ">> Initialization vector");
		emit_int("bytes_written", written);
		emit_hex("output", output, written);

		memset(decoded, 0xcc, sizeof(decoded));
		size = 0;
		if (lanplus_decrypt_payload(IPMI_CRYPT_AES_CBC_128, key, output,
		                            written, decoded, &size)) {
			fprintf(stderr, "gen_vectors: decrypt_payload failed\n");
			exit(1);
		}
		emit_int("decrypted_size", size);
		emit_hex("decrypted", decoded, size);
	}

	/* IPMI_CRYPT_NONE: encrypt writes nothing, decrypt copies everything. */
	fill(input, 40, 5);
	memset(output, 0xcc, sizeof(output));
	written = 0;
	lanplus_encrypt_payload(IPMI_CRYPT_NONE, NULL, input, 40, output, &written);
	emit_case("payload/none/40");
	emit_hex("input", input, 40);
	emit_int("bytes_written", written);
	emit_hex("output", output, written);
	memset(decoded, 0xcc, sizeof(decoded));
	size = 0;
	lanplus_decrypt_payload(IPMI_CRYPT_NONE, NULL, input, 40, decoded, &size);
	emit_int("decrypted_size", size);
	emit_hex("decrypted", decoded, size);

	close_out();
}

/* ------------------------------------------------------------------ */
/* lanplus_crypt.c: RAKP 1-4 key derivation                             */
/* ------------------------------------------------------------------ */

struct rakp_case {
	const char *name;
	uint8_t auth_alg;
	uint8_t integrity_alg;
	const char *username;
	const char *password;
	const char *kg;
	const char *oem;
	uint8_t requested_role;
	uint8_t privlvl;
};

static void gen_rakp_case(const struct rakp_case *tc)
{
	struct ipmi_session session;
	struct ipmi_intf intf;
	uint8_t bmc_mac[IPMI_MAX_MD_SIZE];
	uint8_t rakp3[IPMI_MAX_MD_SIZE];
	uint32_t rakp3_len = 0;
	int matches;

	memset(&session, 0, sizeof(session));
	memset(&intf, 0, sizeof(intf));

	active_oem = tc->oem;

	snprintf((char *)intf.ssn_params.username,
	         sizeof(intf.ssn_params.username), "%s", tc->username);
	snprintf((char *)session.authcode, sizeof(session.authcode), "%s",
	         tc->password);
	snprintf((char *)intf.ssn_params.kg, sizeof(intf.ssn_params.kg), "%s",
	         tc->kg);
	intf.ssn_params.privlvl = tc->privlvl;

	session.v2_data.auth_alg = tc->auth_alg;
	session.v2_data.integrity_alg = tc->integrity_alg;
	session.v2_data.crypt_alg = IPMI_CRYPT_AES_CBC_128;
	session.v2_data.console_id = 0xa0a1a2a3u;
	session.v2_data.bmc_id = 0xb0b1b2b3u;
	session.v2_data.requested_role = tc->requested_role;
	fill(session.v2_data.console_rand, 16, 101);
	fill(session.v2_data.bmc_rand, 16, 102);
	fill(session.v2_data.bmc_guid, 16, 103);

	emit_case(tc->name);
	emit_int("auth_alg", tc->auth_alg);
	emit_int("integrity_alg", tc->integrity_alg);
	emit_str("username", tc->username);
	emit_str("oem", tc->oem ? tc->oem : "");
	emit_int("requested_role", tc->requested_role);
	emit_int("privlvl", tc->privlvl);
	emit_hex("console_id", (const uint8_t *)&session.v2_data.console_id, 4);
	emit_hex("bmc_id", (const uint8_t *)&session.v2_data.bmc_id, 4);
	emit_hex("console_rand", session.v2_data.console_rand, 16);
	emit_hex("bmc_rand", session.v2_data.bmc_rand, 16);
	emit_hex("bmc_guid", session.v2_data.bmc_guid, 16);
	emit_hex("session_authcode", session.authcode, IPMI_AUTHCODE_BUFFER_SIZE);
	emit_hex("session_kg", intf.ssn_params.kg, IPMI_AUTHCODE_BUFFER_SIZE);

	/* RAKP 2: run once with a bogus MAC to capture what the console computes. */
	memset(bmc_mac, 0, sizeof(bmc_mac));
	capture_reset();
	matches = lanplus_rakp2_hmac_matches(&session, bmc_mac, &intf);
	emit_int("rakp2_matches_zero", matches);
	if (tc->auth_alg != IPMI_AUTH_RAKP_NONE) {
		emit_capture("rakp2_input", ">> rakp2 mac input buffer");
		emit_capture("rakp2_key", ">> rakp2 mac key");
		emit_capture("rakp2_mac", ">> rakp2 mac as computed by the remote console");
		{
			int len;
			const uint8_t *mac = capture_get(
				">> rakp2 mac as computed by the remote console", &len);
			memcpy(bmc_mac, mac, len);
		}
		capture_reset();
		emit_int("rakp2_matches_real",
		         lanplus_rakp2_hmac_matches(&session, bmc_mac, &intf));
	}

	/* RAKP 3 */
	capture_reset();
	memset(rakp3, 0, sizeof(rakp3));
	emit_int("rakp3_rc",
	         lanplus_generate_rakp3_authcode(rakp3, &session, &rakp3_len, &intf));
	if (tc->auth_alg != IPMI_AUTH_RAKP_NONE)
		emit_capture("rakp3_input", ">> rakp3 mac input buffer");
	emit_int("rakp3_len", rakp3_len);
	emit_hex("rakp3_mac", rakp3, (int)rakp3_len);

	/* SIK, K1, K2 */
	capture_reset();
	emit_int("sik_rc", lanplus_generate_sik(&session, &intf));
	if (tc->auth_alg != IPMI_AUTH_RAKP_NONE)
		emit_capture("sik_input", "session integrity key input");
	emit_int("sik_len", session.v2_data.sik_len);
	emit_hex("sik", session.v2_data.sik, session.v2_data.sik_len);

	capture_reset();
	emit_int("k1_rc", lanplus_generate_k1(&session));
	emit_int("k1_len", session.v2_data.k1_len);
	/* With IPMI_AUTH_RAKP_NONE the C fills 20 bytes of K1 but never sets
	 * k1_len, so the 20 bytes are recorded separately from the length. */
	emit_hex("k1", session.v2_data.k1, IPMI_MAX_MD_SIZE);

	capture_reset();
	emit_int("k2_rc", lanplus_generate_k2(&session));
	emit_int("k2_len", session.v2_data.k2_len);
	emit_hex("k2", session.v2_data.k2, IPMI_MAX_MD_SIZE);

	/* RAKP 4, keyed with the SIK just derived. */
	memset(bmc_mac, 0, sizeof(bmc_mac));
	capture_reset();
	matches = lanplus_rakp4_hmac_matches(&session, bmc_mac, &intf);
	emit_int("rakp4_matches_zero", matches);
	if (tc->auth_alg != IPMI_AUTH_RAKP_NONE) {
		emit_capture("rakp4_input", ">> rakp4 mac input buffer");
		emit_capture("rakp4_key", ">> rakp4 mac key (sik)");
		emit_capture("rakp4_mac", ">> rakp4 mac as computed by the remote console");
		{
			int len;
			const uint8_t *mac = capture_get(
				">> rakp4 mac as computed by the remote console", &len);
			memcpy(bmc_mac, mac, len);
		}
		capture_reset();
		emit_int("rakp4_matches_real",
		         lanplus_rakp4_hmac_matches(&session, bmc_mac, &intf));
	}

	/* Integrity check value over a synthetic RMCP+ packet. */
	if (tc->integrity_alg != IPMI_INTEGRITY_NONE) {
		struct ipmi_rs rs;
		uint32_t authcode_length;
		uint8_t generated[IPMI_MAX_MD_SIZE];
		uint32_t generated_len = 0;
		int payload_len = 96;

		switch (tc->integrity_alg) {
		case IPMI_INTEGRITY_HMAC_SHA1_96:
			authcode_length = IPMI_SHA1_AUTHCODE_SIZE;
			break;
		case IPMI_INTEGRITY_HMAC_MD5_128:
			authcode_length = IPMI_HMAC_MD5_AUTHCODE_SIZE;
			break;
		default:
			authcode_length = IPMI_HMAC_SHA256_AUTHCODE_SIZE;
			break;
		}

		memset(&rs, 0, sizeof(rs));
		fill(rs.data, payload_len, 55);
		rs.data_len = payload_len;
		rs.session.authtype = IPMI_SESSION_AUTHTYPE_RMCP_PLUS;
		rs.session.bAuthenticated = 1;
		session.v2_data.session_state = LANPLUS_STATE_ACTIVE;

		/* Compute the expected authcode with the same primitive the C
		 * uses, then splice it into the packet so the check passes. */
		lanplus_HMAC(session.v2_data.integrity_alg,
		             session.v2_data.k1, session.v2_data.k1_len,
		             rs.data + IPMI_LANPLUS_OFFSET_AUTHTYPE,
		             rs.data_len - IPMI_LANPLUS_OFFSET_AUTHTYPE
		                 - (int)authcode_length,
		             generated, &generated_len);
		memcpy(rs.data + rs.data_len - authcode_length, generated,
		       authcode_length);

		capture_reset();
		emit_int("integrity_authcode_length", authcode_length);
		emit_hex("integrity_packet", rs.data, rs.data_len);
		emit_hex("integrity_authcode", generated, (int)generated_len);
		emit_int("integrity_valid",
		         lanplus_has_valid_auth_code(&rs, &session));

		/* Flip one byte of the packet body: the check must now fail. */
		rs.data[10] ^= 0xff;
		capture_reset();
		emit_int("integrity_valid_tampered",
		         lanplus_has_valid_auth_code(&rs, &session));
	}

	active_oem = NULL;
}

static void gen_rakp(const char *dir)
{
	static const struct rakp_case cases[] = {
		{ "rakp/sha1/admin",       IPMI_AUTH_RAKP_HMAC_SHA1,
		  IPMI_INTEGRITY_HMAC_SHA1_96, "admin", "password", "", NULL, 0x14, 4 },
		{ "rakp/sha1/nouser",      IPMI_AUTH_RAKP_HMAC_SHA1,
		  IPMI_INTEGRITY_HMAC_SHA1_96, "", "password", "", NULL, 0x14, 4 },
		{ "rakp/sha1/kg",          IPMI_AUTH_RAKP_HMAC_SHA1,
		  IPMI_INTEGRITY_HMAC_SHA1_96, "admin", "password", "bmckey", NULL, 0x14, 4 },
		{ "rakp/sha1/longuser",    IPMI_AUTH_RAKP_HMAC_SHA1,
		  IPMI_INTEGRITY_HMAC_SHA1_96, "0123456789abcdef", "0123456789abcdefghij",
		  "0123456789abcdefghij", NULL, 0x04, 2 },
		{ "rakp/md5/admin",        IPMI_AUTH_RAKP_HMAC_MD5,
		  IPMI_INTEGRITY_HMAC_MD5_128, "admin", "password", "", NULL, 0x14, 4 },
		{ "rakp/md5/kg",           IPMI_AUTH_RAKP_HMAC_MD5,
		  IPMI_INTEGRITY_HMAC_MD5_128, "operator", "secret", "bmckey", NULL, 0x13, 3 },
		{ "rakp/sha256/admin",     IPMI_AUTH_RAKP_HMAC_SHA256,
		  IPMI_INTEGRITY_HMAC_SHA256_128, "admin", "password", "", NULL, 0x14, 4 },
		{ "rakp/sha256/kg",        IPMI_AUTH_RAKP_HMAC_SHA256,
		  IPMI_INTEGRITY_HMAC_SHA256_128, "admin", "password", "bmckey", NULL, 0x14, 4 },
		{ "rakp/sha1/i82571spt",   IPMI_AUTH_RAKP_HMAC_SHA1,
		  IPMI_INTEGRITY_HMAC_SHA1_96, "admin", "password", "", "i82571spt", 0x14, 4 },
		{ "rakp/sha1/intelplus",   IPMI_AUTH_RAKP_HMAC_SHA1,
		  IPMI_INTEGRITY_HMAC_SHA1_96, "admin", "password", "", "intelplus", 0x14, 4 },
		{ "rakp/md5/intelplus",    IPMI_AUTH_RAKP_HMAC_MD5,
		  IPMI_INTEGRITY_HMAC_MD5_128, "admin", "password", "", "intelplus", 0x14, 4 },
		{ "rakp/none/noauth",      IPMI_AUTH_RAKP_NONE,
		  IPMI_INTEGRITY_NONE, "admin", "password", "", NULL, 0x14, 4 },
	};
	size_t i;

	open_out(dir, "rakp.txt",
	         "RMCP+ RAKP key derivation (src/plugins/lanplus/lanplus_crypt.c)");

	for (i = 0; i < sizeof(cases) / sizeof(cases[0]); ++i)
		gen_rakp_case(&cases[i]);

	close_out();
}

/* ------------------------------------------------------------------ */

int main(int argc, char **argv)
{
	const char *dir = (argc > 1) ? argv[1] : "tests/crypto/vectors";

	gen_md5(dir);
	gen_auth(dir);
	gen_hmac(dir);
	gen_aes(dir);
	gen_payload(dir);
	gen_rakp(dir);
	return 0;
}
