//! Compile-time C header checks for the generated lookup tables.
//!
//! Generated by `tools/gen_strings.zig` alongside `strings_tables.zig`.
//! Imported at the selected export boundary and by the ABI test root, not by
//! standalone lookup rules or table data.

const c = @import("ipmi_c");
const tables = @import("strings_tables.zig");
const types = @import("table_types.zig");

const ValStr = types.ValStr;
const OemValStr = types.OemValStr;

/// Fails the build when `<ipmitool/ipmi_strings.h>` declares an exported table
/// with a different element type than the one this module defines it with.
/// This is the data-symbol counterpart of `abi.assertCallSignature`.
fn assertTableType(comptime Elem: type, comptime CTable: type) void {
    const info = @typeInfo(CTable);
    if (info != .pointer) @compileError("expected a C array-to-pointer decay");
    const CElem = info.pointer.child;
    if (@sizeOf(Elem) != @sizeOf(CElem) or @alignOf(Elem) != @alignOf(CElem)) {
        @compileError("element layout differs from " ++ @typeName(CElem));
    }
}

/// Fails the build when a value copied out of a C header no longer matches it.
fn assertConst(comptime mine: comptime_int, comptime theirs: anytype) void {
    if (mine != theirs) @compileError("constant drifted from the C header");
}

comptime {
    if (tables.have_crypto_sha256 != @hasDecl(c, "HAVE_CRYPTO_SHA256"))
        @compileError("SHA256 table feature drifted from the C config header");

    assertTableType(OemValStr, @TypeOf(c.ipmi_oem_product_info));
    assertTableType(?[*:0]const u8, @TypeOf(c.ipmi_generic_sensor_type_vals));
    assertTableType(OemValStr, @TypeOf(c.ipmi_oem_sensor_type_vals));
    assertTableType(ValStr, @TypeOf(c.ipmi_netfn_vals));
    assertTableType(ValStr, @TypeOf(c.ipmi_bit_rate_vals));
    assertTableType(ValStr, @TypeOf(c.ipmi_channel_activity_type_vals));
    assertTableType(ValStr, @TypeOf(c.ipmi_privlvl_vals));
    assertTableType(ValStr, @TypeOf(c.ipmi_set_in_progress_vals));
    assertTableType(ValStr, @TypeOf(c.ipmi_authtype_session_vals));
    assertTableType(ValStr, @TypeOf(c.ipmi_authtype_vals));
    assertTableType(ValStr, @TypeOf(c.entity_id_vals));
    assertTableType(ValStr, @TypeOf(c.entity_device_type_vals));
    assertTableType(ValStr, @TypeOf(c.ipmi_channel_protocol_vals));
    assertTableType(ValStr, @TypeOf(c.ipmi_channel_medium_vals));
    assertTableType(ValStr, @TypeOf(c.completion_code_vals));
    assertTableType(ValStr, @TypeOf(c.ipmi_chassis_power_control_vals));
    assertTableType(ValStr, @TypeOf(c.ipmi_chassis_restart_cause_vals));
    assertTableType(ValStr, @TypeOf(c.ipmi_auth_algorithms));
    assertTableType(ValStr, @TypeOf(c.ipmi_integrity_algorithms));
    assertTableType(ValStr, @TypeOf(c.ipmi_encryption_algorithms));
    assertTableType(ValStr, @TypeOf(c.ipmi_user_enable_status_vals));
    assertTableType(ValStr, @TypeOf(c.picmg_frucontrol_vals));
    assertTableType(ValStr, @TypeOf(c.picmg_clk_family_vals));
    assertTableType(OemValStr, @TypeOf(c.picmg_clk_accuracy_vals));
    assertTableType(OemValStr, @TypeOf(c.picmg_clk_resource_vals));
    assertTableType(OemValStr, @TypeOf(c.picmg_clk_id_vals));
    assertTableType(ValStr, @TypeOf(c.picmg_busres_id_vals));
    assertTableType(ValStr, @TypeOf(c.picmg_busres_board_cmd_vals));
    assertTableType(ValStr, @TypeOf(c.picmg_busres_shmc_cmd_vals));
    assertTableType(OemValStr, @TypeOf(c.picmg_busres_board_status_vals));
    assertTableType(OemValStr, @TypeOf(c.picmg_busres_shmc_status_vals));

    assertConst(tables.ipmi_1_5_auth_type_bit_md2, c.IPMI_1_5_AUTH_TYPE_BIT_MD2);
    assertConst(tables.ipmi_1_5_auth_type_bit_md5, c.IPMI_1_5_AUTH_TYPE_BIT_MD5);
    assertConst(tables.ipmi_1_5_auth_type_bit_none, c.IPMI_1_5_AUTH_TYPE_BIT_NONE);
    assertConst(tables.ipmi_1_5_auth_type_bit_oem, c.IPMI_1_5_AUTH_TYPE_BIT_OEM);
    assertConst(tables.ipmi_1_5_auth_type_bit_password, c.IPMI_1_5_AUTH_TYPE_BIT_PASSWORD);
    assertConst(tables.ipmi_auth_rakp_hmac_md5, c.IPMI_AUTH_RAKP_HMAC_MD5);
    assertConst(tables.ipmi_auth_rakp_hmac_sha1, c.IPMI_AUTH_RAKP_HMAC_SHA1);
    assertConst(tables.ipmi_auth_rakp_hmac_sha256, c.IPMI_AUTH_RAKP_HMAC_SHA256);
    assertConst(tables.ipmi_auth_rakp_none, c.IPMI_AUTH_RAKP_NONE);
    assertConst(tables.ipmi_channel_medium_icmb_09, c.IPMI_CHANNEL_MEDIUM_ICMB_09);
    assertConst(tables.ipmi_channel_medium_icmb_1, c.IPMI_CHANNEL_MEDIUM_ICMB_1);
    assertConst(tables.ipmi_channel_medium_ipmb_i2c, c.IPMI_CHANNEL_MEDIUM_IPMB_I2C);
    assertConst(tables.ipmi_channel_medium_lan, c.IPMI_CHANNEL_MEDIUM_LAN);
    assertConst(tables.ipmi_channel_medium_lan_other, c.IPMI_CHANNEL_MEDIUM_LAN_OTHER);
    assertConst(tables.ipmi_channel_medium_reserved, c.IPMI_CHANNEL_MEDIUM_RESERVED);
    assertConst(tables.ipmi_channel_medium_serial, c.IPMI_CHANNEL_MEDIUM_SERIAL);
    assertConst(tables.ipmi_channel_medium_smbus_1, c.IPMI_CHANNEL_MEDIUM_SMBUS_1);
    assertConst(tables.ipmi_channel_medium_smbus_2, c.IPMI_CHANNEL_MEDIUM_SMBUS_2);
    assertConst(tables.ipmi_channel_medium_smbus_pci, c.IPMI_CHANNEL_MEDIUM_SMBUS_PCI);
    assertConst(tables.ipmi_channel_medium_system, c.IPMI_CHANNEL_MEDIUM_SYSTEM);
    assertConst(tables.ipmi_channel_medium_usb_1, c.IPMI_CHANNEL_MEDIUM_USB_1);
    assertConst(tables.ipmi_channel_medium_usb_2, c.IPMI_CHANNEL_MEDIUM_USB_2);
    assertConst(tables.ipmi_chassis_ctl_acpi_soft, c.IPMI_CHASSIS_CTL_ACPI_SOFT);
    assertConst(tables.ipmi_chassis_ctl_hard_reset, c.IPMI_CHASSIS_CTL_HARD_RESET);
    assertConst(tables.ipmi_chassis_ctl_power_cycle, c.IPMI_CHASSIS_CTL_POWER_CYCLE);
    assertConst(tables.ipmi_chassis_ctl_power_down, c.IPMI_CHASSIS_CTL_POWER_DOWN);
    assertConst(tables.ipmi_chassis_ctl_power_up, c.IPMI_CHASSIS_CTL_POWER_UP);
    assertConst(tables.ipmi_chassis_ctl_pulse_diag, c.IPMI_CHASSIS_CTL_PULSE_DIAG);
    assertConst(tables.ipmi_crypt_aes_cbc_128, c.IPMI_CRYPT_AES_CBC_128);
    assertConst(tables.ipmi_crypt_none, c.IPMI_CRYPT_NONE);
    assertConst(tables.ipmi_crypt_xrc4_128, c.IPMI_CRYPT_XRC4_128);
    assertConst(tables.ipmi_crypt_xrc4_40, c.IPMI_CRYPT_XRC4_40);
    assertConst(tables.ipmi_integrity_hmac_md5_128, c.IPMI_INTEGRITY_HMAC_MD5_128);
    assertConst(tables.ipmi_integrity_hmac_sha1_96, c.IPMI_INTEGRITY_HMAC_SHA1_96);
    assertConst(tables.ipmi_integrity_hmac_sha256_128, c.IPMI_INTEGRITY_HMAC_SHA256_128);
    assertConst(tables.ipmi_integrity_md5_128, c.IPMI_INTEGRITY_MD5_128);
    assertConst(tables.ipmi_integrity_none, c.IPMI_INTEGRITY_NONE);
    assertConst(tables.ipmi_netfn_app, c.IPMI_NETFN_APP);
    assertConst(tables.ipmi_netfn_bridge, c.IPMI_NETFN_BRIDGE);
    assertConst(tables.ipmi_netfn_chassis, c.IPMI_NETFN_CHASSIS);
    assertConst(tables.ipmi_netfn_firmware, c.IPMI_NETFN_FIRMWARE);
    assertConst(tables.ipmi_netfn_se, c.IPMI_NETFN_SE);
    assertConst(tables.ipmi_netfn_storage, c.IPMI_NETFN_STORAGE);
    assertConst(tables.ipmi_netfn_transport, c.IPMI_NETFN_TRANSPORT);
    assertConst(tables.ipmi_oem_adlink_24339, c.IPMI_OEM_ADLINK_24339);
    assertConst(tables.ipmi_oem_advantech, c.IPMI_OEM_ADVANTECH);
    assertConst(tables.ipmi_oem_broadcom, c.IPMI_OEM_BROADCOM);
    assertConst(tables.ipmi_oem_debug, c.IPMI_OEM_DEBUG);
    assertConst(tables.ipmi_oem_ericsson, c.IPMI_OEM_ERICSSON);
    assertConst(tables.ipmi_oem_intel, c.IPMI_OEM_INTEL);
    assertConst(tables.ipmi_oem_kontron, c.IPMI_OEM_KONTRON);
    assertConst(tables.ipmi_oem_picmg, c.IPMI_OEM_PICMG);
    assertConst(tables.ipmi_oem_reserved, c.IPMI_OEM_RESERVED);
    assertConst(tables.ipmi_oem_supermicro, c.IPMI_OEM_SUPERMICRO);
    assertConst(tables.ipmi_oem_unknown, c.IPMI_OEM_UNKNOWN);
    assertConst(tables.ipmi_oem_vita, c.IPMI_OEM_VITA);
    assertConst(tables.ipmi_oem_yadro, c.IPMI_OEM_YADRO);
    assertConst(tables.ipmi_session_authtype_md2, c.IPMI_SESSION_AUTHTYPE_MD2);
    assertConst(tables.ipmi_session_authtype_md5, c.IPMI_SESSION_AUTHTYPE_MD5);
    assertConst(tables.ipmi_session_authtype_none, c.IPMI_SESSION_AUTHTYPE_NONE);
    assertConst(tables.ipmi_session_authtype_oem, c.IPMI_SESSION_AUTHTYPE_OEM);
    assertConst(tables.ipmi_session_authtype_password, c.IPMI_SESSION_AUTHTYPE_PASSWORD);
    assertConst(tables.ipmi_session_authtype_rmcp_plus, c.IPMI_SESSION_AUTHTYPE_RMCP_PLUS);
    assertConst(tables.ipmi_session_priv_admin, c.IPMI_SESSION_PRIV_ADMIN);
    assertConst(tables.ipmi_session_priv_callback, c.IPMI_SESSION_PRIV_CALLBACK);
    assertConst(tables.ipmi_session_priv_noaccess, c.IPMI_SESSION_PRIV_NOACCESS);
    assertConst(tables.ipmi_session_priv_oem, c.IPMI_SESSION_PRIV_OEM);
    assertConst(tables.ipmi_session_priv_operator, c.IPMI_SESSION_PRIV_OPERATOR);
    assertConst(tables.ipmi_session_priv_user, c.IPMI_SESSION_PRIV_USER);
    assertConst(tables.ipmi_set_in_progress_commit_write, c.IPMI_SET_IN_PROGRESS_COMMIT_WRITE);
    assertConst(tables.ipmi_set_in_progress_in_progress, c.IPMI_SET_IN_PROGRESS_IN_PROGRESS);
    assertConst(tables.ipmi_set_in_progress_set_complete, c.IPMI_SET_IN_PROGRESS_SET_COMPLETE);
}
